"""Per-parameter schema definitions for all OSIRIS input deck sections.

Each parameter is defined by its Fortran type, Python type, dimensions, default value,
constraints, and description -- sourced from the Fortran namelist definitions in the
OSIRIS source code.
"""

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ParamSpec:
    """Specification for a single parameter within an OSIRIS section.

    Derived from the corresponding Fortran namelist declaration and
    default-value/validation logic in the section's read_input subroutine.
    """

    name: str
    fortran_type: str  # e.g. "real(p_double)", "integer", "logical", "character(len=20)"
    python_type: type  # float, int, bool, str
    dimensions: tuple[int | str, ...] | None = None
    # None  -> scalar
    # ()    -> scalar (explicit)
    # (3,)  -> 1D array with 3 elements
    # ("p_x_dim",) -> size depends on compile-time dimension
    # (2, "p_x_dim") -> 2D: 2 walls x spatial dimensions
    default: Any = None
    required: bool = False  # Fortran namelist: individual params always have defaults
    constraints: list[str] | None = None  # e.g. ["> 0", "in (cartesian, cylindrical)"]
    condition: str | None = None  # e.g. "if_move == 1" or "__HAS_SPIN__"
    description: str = ""


# ============================================================================
# Section parameter definitions
# ============================================================================

# ---- simulation (os-main.f03, namelist /nl_simulation/) ----
_SIMULATION_PARAMS: list[ParamSpec] = [
    ParamSpec("random_seed", "integer", int,
              description="Random number generator seed (0 = use system clock)"),
    ParamSpec("random_algorithm", "character(len=20)", str,
              default="default",
              description="Random number generator algorithm type"),
    ParamSpec("algorithm", "character(len=20)", str,
              default="standard",
              constraints=["in (standard, hd-hybrid)"],
              description="Simulation algorithm type"),
    ParamSpec("omega_p0", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Reference plasma frequency"),
    ParamSpec("n0", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Reference density"),
    ParamSpec("gamma", "real(p_double)", float,
              default=1.0, constraints=[">= 1"],
              description="Relativistic factor of the boosted reference frame"),
    ParamSpec("ndump_prof", "integer", int,
              default=0, constraints=[">= 0"],
              description="Timestep frequency for profiling output (0 = disabled)"),
    ParamSpec("wall_clock_limit", "character(len=16)", str,
              default="",
              description="Wall clock time limit (empty = no limit, format h:m:s)"),
    ParamSpec("wall_clock_check", "integer", int,
              default=-1,
              description="Timestep frequency for wall clock check (-1 = disabled)"),
    ParamSpec("wall_clock_checkpoint", "logical", bool,
              default=True,
              description="Write checkpoint before wall clock limit"),
    ParamSpec("prof_start", "integer", int,
              default=-1,
              description="First timestep to start profiling (-1 = disabled)"),
    ParamSpec("prof_end", "integer", int,
              default=None,  # huge(prof_start) — effectively max int
              description="Last timestep for profiling"),
    ParamSpec("file_format", "character(len=20)", str,
              default="zdf", constraints=["in (zdf, hdf5)"],
              description="Output file format (zdf or hdf5)"),
    ParamSpec("parallel_io", "character(len=20)", str,
              default="mpi",
              description="Parallel I/O strategy"),
    ParamSpec("enforce_rng_constancy", "logical", bool,
              default=False,
              description="Enforce random number generator consistency across restarts"),
]

# ---- node_conf (os-nconf.f03, namelist /nl_node_conf/) ----
_NODE_CONF_PARAMS: list[ParamSpec] = [
    ParamSpec("node_number", "integer", int,
              dimensions=("p_x_dim",), default=1, constraints=["> 0"],
              description="Number of MPI nodes per spatial dimension"),
    ParamSpec("if_periodic", "logical", bool,
              dimensions=("p_x_dim",), default=False,
              description="Whether to use periodic boundaries per spatial dimension"),
    ParamSpec("n_threads", "integer", int,
              default=1, constraints=[">= 1"],
              description="Number of OpenMP threads per MPI process"),
    ParamSpec("topology", "character(len=16)", str,
              default="mpi", constraints=["in (mpi, old, bgq)"],
              description="MPI topology type"),
]

# ---- grid (grid/os-grid-define.f03, namelist /nl_grid/) ----
_GRID_PARAMS: list[ParamSpec] = [
    ParamSpec("nx_p", "integer", int,
              dimensions=("p_x_dim",), default=0, constraints=["> 0"],
              description="Number of grid points per spatial dimension"),
    ParamSpec("coordinates", "character(len=16)", str,
              default="cartesian", constraints=["in (cartesian, cylindrical)"],
              description="Coordinate system type"),
    ParamSpec("io_nmerge", "integer", int,
              dimensions=("p_x_dim",), default=1, constraints=[">= 1"],
              description="Number of I/O merges per spatial dimension"),
    ParamSpec("io_merge_type", "character(len=16)", str,
              default="point2point", constraints=["in (none, point2point, gather)"],
              description="I/O merge communication type"),
    ParamSpec("load_balance", "logical", bool,
              dimensions=("p_x_dim",), default=False,
              description="Enable dynamic load balancing per dimension"),
    ParamSpec("lb_type", "character(len=16)", str,
              default="none",
              constraints=["in (none, test, static, dynamic, expression)"],
              description="Load balancing type"),
    ParamSpec("lb_gather", "character(len=16)", str,
              default="sum", constraints=["in (sum, max)"],
              condition="lb_type == 'dynamic'",
              description="Load balancing gather operation type"),
    ParamSpec("n_dynamic", "integer", int,
              default=-1,
              description="Timestep interval for dynamic load balancing (-1 = off)"),
    ParamSpec("start_load_balance", "integer", int,
              default=-1,
              description="First timestep to begin load balancing (-1 = off)"),
    ParamSpec("balance_on_start", "logical", bool,
              default=False,
              description="Perform dynamic load balancing on the first timestep"),
    ParamSpec("max_imbalance", "real(p_single)", float,
              default=0.0,
              condition="lb_type == 'dynamic'",
              description="Maximum allowed load imbalance threshold"),
    ParamSpec("cell_weight", "real(p_single)", float,
              default=0.0, constraints=[">= 0"],
              description="Per-grid-cell weight for load balancing"),
    ParamSpec("ndump_global_load", "integer", int,
              default=0, constraints=[">= 0"],
              description="Frequency of global load diagnostics (0 = disabled)"),
    ParamSpec("ndump_node_load", "integer", int,
              default=0, constraints=[">= 0"],
              description="Frequency of per-node load diagnostics (0 = disabled)"),
    ParamSpec("ndump_grid_load", "integer", int,
              default=0, constraints=[">= 0"],
              description="Frequency of per-grid-cell load diagnostics (0 = disabled)"),
    ParamSpec("spatial_loaddensity", "character(len=1024)", str,
              default="NO FUNCTION DEFINED",
              condition="lb_type == 'expression'",
              description="Mathematical expression for spatial load density"),
]

# ---- time_step (os-tstep.f90, namelist /nl_time_step/) ----
_TIME_STEP_PARAMS: list[ParamSpec] = [
    ParamSpec("dt", "real(p_double)", float,
              default=0.0, constraints=["!= 0"],
              description="Simulation time step"),
    ParamSpec("ndump", "integer", int,
              default=0, constraints=[">= 0"],
              description="Main reporting/output timestep frequency"),
    ParamSpec("dump_start", "integer", int,
              default=0, constraints=[">= 0"],
              description="First timestep to begin diagnostic output"),
]

# ---- space (os-space.f90, namelist /nl_space/) ----
_SPACE_PARAMS: list[ParamSpec] = [
    ParamSpec("xmin", "real(p_double)", float,
              dimensions=(3,), default=0.0,  # p_max_dim = 3
              description="Minimum spatial coordinate per dimension"),
    ParamSpec("xmax", "real(p_double)", float,
              dimensions=(3,), default=0.0,  # p_max_dim = 3
              description="Maximum spatial coordinate per dimension"),
    ParamSpec("if_move", "logical", bool,
              dimensions=(3,), default=False,  # p_max_dim = 3
              description="Enable moving window per dimension"),
    ParamSpec("move_u", "real(p_double)", float,
              default=-1.0,
              description="Moving window 4-velocity (u = gamma*beta; < 0 = disabled)"),
]

# ---- time (os-time.f90, namelist /nl_time/) ----
_TIME_PARAMS: list[ParamSpec] = [
    ParamSpec("tmin", "real(p_double)", float,
              default=0.0,
              description="Simulation start time"),
    ParamSpec("tmax", "real(p_double)", float,
              default=0.0,
              description="Simulation end time"),
]

# ---- emf_bound (emf/boundary/os-emf-boundary.f90, namelist /nl_emf_bound/) ----
_EMF_BOUND_PARAMS: list[ParamSpec] = [
    ParamSpec("type", "character(len=20)", str,
              dimensions=(2, "p_x_dim"),
              default="---",
              constraints=["in (axial, lindman, lindmann, vpml, open, pec, conducting, pmc, reflecting, ---)"],
              description="EMF boundary condition type per dimension per wall"),
    ParamSpec("vpml_bnd_size", "integer", int,
              default=8, constraints=["> 0"],
              description="Number of grid cells in VPML boundary layer"),
    ParamSpec("vpml_diffuse", "logical", bool,
              dimensions=(2, "p_x_dim"), default=False,
              description="Enable VPML diffusive behavior per dimension per wall"),
]

# ---- el_mag_fld (emf/os-emf.f03, namelist /nl_el_mag_fld/) ----
_EL_MAG_FLD_PARAMS: list[ParamSpec] = [
    # Solver
    ParamSpec("solver", "character(len=20)", str,
              default="yee",
              description="Electromagnetic field solver type"),
    # Smoothing
    ParamSpec("smooth_type", "character(len=20)", str,
              default="none", constraints=["in (none, stand, nci, local)"],
              description="EMF smoothing type"),
    ParamSpec("smooth_niter", "integer", int,
              default=1, constraints=[">= 1"],
              description="Number of smoothing iterations (for local smoothing)"),
    ParamSpec("smooth_nmax", "integer", int,
              default=-1,
              description="Maximum grid dimension to apply smoothing"),
    # Initial B-field
    ParamSpec("type_init_b", "character(len=20)", str,
              dimensions=(3,), default="uniform",  # p_f_dim = 3
              constraints=["in (uniform, 'math func', dipole)"],
              description="Initial B-field type per field component"),
    ParamSpec("init_b0", "real(p_double)", float,
              dimensions=(3,), default=0.0,  # p_f_dim = 3
              description="Uniform initial B-field value per component"),
    ParamSpec("init_b_mfunc", "character(len=1024)", str,
              dimensions=(3,), default="NO_FUNCTION_SUPPLIED!",
              condition="type_init_b == 'math func'",
              description="Initial B-field math expression per component"),
    ParamSpec("init_dipole_b_m", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              condition="type_init_b == 'dipole'",
              description="Dipole magnetic moment per field component"),
    ParamSpec("init_dipole_b_x0", "real(p_double)", float,
              dimensions=("p_x_dim",), default=0.0,
              condition="type_init_b == 'dipole'",
              description="Dipole B-field center position"),
    ParamSpec("init_dipole_b_r0", "real(p_double)", float,
              default=0.001,
              condition="type_init_b == 'dipole'",
              description="Dipole B-field characteristic radius"),
    # Initial E-field
    ParamSpec("type_init_e", "character(len=20)", str,
              dimensions=(3,), default="uniform",  # p_f_dim = 3
              constraints=["in (uniform, 'math func', dipole)"],
              description="Initial E-field type per field component"),
    ParamSpec("init_e0", "real(p_double)", float,
              dimensions=(3,), default=0.0,  # p_f_dim = 3
              description="Uniform initial E-field value per component"),
    ParamSpec("init_e_mfunc", "character(len=1024)", str,
              dimensions=(3,), default="NO_FUNCTION_SUPPLIED!",
              condition="type_init_e == 'math func'",
              description="Initial E-field math expression per component"),
    ParamSpec("init_dipole_e_p", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              condition="type_init_e == 'dipole'",
              description="Dipole electric moment per field component"),
    ParamSpec("init_dipole_e_x0", "real(p_double)", float,
              dimensions=("p_x_dim",), default=0.0,
              condition="type_init_e == 'dipole'",
              description="Dipole E-field center position"),
    ParamSpec("init_dipole_e_r0", "real(p_double)", float,
              default=0.001,
              condition="type_init_e == 'dipole'",
              description="Dipole E-field characteristic radius"),
    # External fields
    ParamSpec("ext_fld", "character(len=20)", str,
              default="none", constraints=["in (none, static, dynamic)"],
              description="External field mode"),
    ParamSpec("type_ext_b", "character(len=20)", str,
              dimensions=(3,), default="uniform",
              constraints=["in (none, uniform, 'math func', dipole)"],
              description="External B-field type per field component"),
    ParamSpec("ext_b0", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              description="Uniform external B-field value per component"),
    ParamSpec("ext_b_mfunc", "character(len=1024)", str,
              dimensions=(3,), default="NO_FUNCTION_SUPPLIED!",
              condition="type_ext_b == 'math func'",
              description="External B-field math expression per component"),
    ParamSpec("ext_dipole_b_m", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              condition="type_ext_b == 'dipole'",
              description="External dipole B-field magnetic moment per component"),
    ParamSpec("ext_dipole_b_x0", "real(p_double)", float,
              dimensions=("p_x_dim",), default=0.0,
              condition="type_ext_b == 'dipole'",
              description="External dipole B-field center position"),
    ParamSpec("ext_dipole_b_r0", "real(p_double)", float,
              default=0.001,
              condition="type_ext_b == 'dipole'",
              description="External dipole B-field characteristic radius"),
    # External E-field
    ParamSpec("type_ext_e", "character(len=20)", str,
              dimensions=(3,), default="uniform",
              constraints=["in (none, uniform, 'math func', dipole)"],
              description="External E-field type per field component"),
    ParamSpec("ext_e0", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              description="Uniform external E-field value per component"),
    ParamSpec("ext_e_mfunc", "character(len=1024)", str,
              dimensions=(3,), default="NO_FUNCTION_SUPPLIED!",
              condition="type_ext_e == 'math func'",
              description="External E-field math expression per component"),
    ParamSpec("ext_dipole_e_p", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              condition="type_ext_e == 'dipole'",
              description="External dipole E-field electric moment per component"),
    ParamSpec("ext_dipole_e_x0", "real(p_double)", float,
              dimensions=("p_x_dim",), default=0.0,
              condition="type_ext_e == 'dipole'",
              description="External dipole E-field center position"),
    ParamSpec("ext_dipole_e_r0", "real(p_double)", float,
              default=0.001,
              condition="type_ext_e == 'dipole'",
              description="External dipole E-field characteristic radius"),
]

# ---- pgc (meta/os-emf-meta.f03, namelist /nl_pgc/) ----
_PGC_PARAMS: list[ParamSpec] = [
    ParamSpec("w0", "real(p_double)", float,
              default=1.0, constraints=["> 0"],
              description="PGC laser spot size (normalized)"),
    ParamSpec("tau", "real(p_double)", float,
              default=1.0, constraints=["> 0"],
              description="PGC laser pulse duration (normalized)"),
    ParamSpec("omega", "real(p_double)", float,
              default=1.0, constraints=["> 0"],
              description="PGC laser frequency (normalized)"),
    ParamSpec("lon_center", "real(p_double)", float,
              default=0.0,
              description="PGC longitudinal center position (normalized)"),
    ParamSpec("per_focus", "real(p_double)", float,
              default=0.0,
              description="PGC focus position (normalized)"),
    ParamSpec("per_center", "real(p_double)", float,
              default=0.0,
              description="PGC perpendicular center position (normalized)"),
    ParamSpec("a0", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="PGC normalized laser amplitude"),
    ParamSpec("free_stream", "logical", bool,
              default=False,
              description="PGC free-stream mode"),
]


# ---- restart (restart/os-restart.f90, namelist /nl_restart/) ----
_RESTART_PARAMS: list[ParamSpec] = [
    ParamSpec("ndump_fac", "integer", int,
              default=0, constraints=[">= 0"],
              description="Restart output frequency (0 = disabled)"),
    ParamSpec("if_restart", "logical", bool,
              default=False,
              description="Enable restart from file"),
    ParamSpec("if_remold", "logical", bool,
              default=False,
              description="Reshape on restart"),
    ParamSpec("ndump_time", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Simulation time interval between restart outputs"),
    ParamSpec("debug_iter", "integer", int,
              default=-1,
              description="Debug iteration for restart (-1 = disabled)"),
]

# ---- particles (particles/os-particles.f03, namelist /nl_particles/) ----
_PARTICLES_PARAMS: list[ParamSpec] = [
    ParamSpec("num_species", "integer", int,
              default=0, constraints=[">= 0"],
              description="Number of particle species"),
    ParamSpec("num_cathode", "integer", int,
              default=0, constraints=[">= 0"],
              description="Number of cathode species"),
    ParamSpec("num_neutral", "integer", int,
              default=0, constraints=[">= 0"],
              description="Number of neutral gas species"),
    ParamSpec("num_neutral_mov_ions", "integer", int,
              default=0, constraints=[">= 0"],
              description="Number of neutral moving ion species"),
    ParamSpec("low_jay_roundoff", "logical", bool,
              default=False,
              description="Use low roundoff error current deposition algorithm"),
    ParamSpec("ndump_fac", "integer", int,
              default=0, constraints=[">= 0"],
              description="Particle report output frequency (0 = disabled)"),
    ParamSpec("ndump_fac_ave", "integer", int,
              default=0, constraints=[">= 0"],
              description="Averaged particle report output frequency"),
    ParamSpec("ndump_fac_lineout", "integer", int,
              default=0, constraints=[">= 0"],
              description="Particle lineout output frequency"),
    ParamSpec("ndump_fac_ene", "integer", int,
              default=0, constraints=[">= 0"],
              description="Particle energy output frequency"),
    ParamSpec("n_ave", "integer", int,
              dimensions=("p_x_dim",), default=-1,
              description="Number of temporal averages for particle reports"),
    ParamSpec("n_tavg", "integer", int,
              default=-1,
              description="Number of timesteps for time-averaged particle reports"),
    ParamSpec("prec", "integer", int,
              default=4,  # p_diag_prec = p_single
              description="Diagnostic output precision"),
    ParamSpec("reports", "character(len=32)", str,
              dimensions=(1024,), default="-",
              description="List of particle report quantities"),
    ParamSpec("interpolation", "character(len=20)", str,
              default="quadratic",
              constraints=["in (linear, quadratic, cubic, quartic)"],
              description="Particle interpolation order"),
    ParamSpec("grid_center", "logical", bool,
              default=False,
              description="Use grid-centered interpolation"),
]

# ---- species (spec/os-species.f03, namelist /nl_species/) ----
_SPECIES_PARAMS: list[ParamSpec] = [
    ParamSpec("name", "character(len=64)", str,
              description="Particle species name"),
    ParamSpec("num_par_max", "integer", int,
              default=0, constraints=[">= 0"],
              description="Maximum number of particles for this species"),
    ParamSpec("n_sort", "integer", int,
              default=25, constraints=[">= 0"],
              description="Timestep interval for particle sorting"),
    ParamSpec("rqm", "real(p_double)", float,
              default=0.0, constraints=["!= 0"],
              description="Charge-to-mass ratio (q/m)"),
    ParamSpec("q_real", "real(p_double)", float,
              default=0.0,
              description="Real charge (macro-particle weight factor)"),
    ParamSpec("num_par_x", "integer", int,
              dimensions=("p_x_dim",), default=-1,
              description="Number of particles per grid cell per spatial dimension"),
    ParamSpec("tot_par_x", "integer", int,
              dimensions=("p_x_dim",), default=-1,
              description="Total number of particles per spatial dimension"),
    ParamSpec("push_type", "character(len=10)", str,
              default="standard",
              constraints=["in (standard, simd, vay, fullrot, euler, beam_accel, pgc, radcool, shear, cond_vay, cary, exact, exact_rr)"],  # noqa: E501
              description="Particle push algorithm type"),
    ParamSpec("push_start_time", "real(p_double)", float,
              default=-1.0,
              description="Time to start pushing particles (-1 = start immediately)"),
    ParamSpec("num_pistons", "integer", int,
              default=0, constraints=[">= 0"],
              description="Number of pistons for this species"),
    ParamSpec("add_tag", "logical", bool,
              default=False,
              description="Add particle identification tags"),
    ParamSpec("free_stream", "logical", bool,
              default=False,
              description="Free-streaming mode (no field interaction)"),
    ParamSpec("init_fields", "logical", bool,
              default=False,
              description="Initialize fields for this species"),
    ParamSpec("if_collide", "logical", bool,
              default=False,
              description="Enable collisions for this species"),
    ParamSpec("if_like_collide", "logical", bool,
              default=False,
              description="Enable like-particle collisions"),
    ParamSpec("init_type", "character(len=16)", str,
              default="standard",
              description="Particle initialization type"),
    ParamSpec("iter_tol", "real(p_double)", float,
              default=0.001,
              description="Convergence tolerance for exact pusher root-finding"),
    ParamSpec("rad_react", "logical", bool,
              default=False,
              description="Enable radiation reaction (exact pusher only)"),
    ParamSpec("anom_mag_moment", "real(p_double)", float,
              default=0.00115965218076,
              condition="__HAS_SPIN__",
              description="Anomalous magnetic moment (spin)"),
]

# ---- profile (spec/psource/os-psource-std.f03, namelist /nl_profile/) ----
# Combined superset of all profile types (standard, beam, file)
_PROFILE_PARAMS: list[ParamSpec] = [
    ParamSpec("profile_type", "character(len=20)", str,
              dimensions=("p_x_dim",), default="default",
              constraints=["in (uniform, gaussian, channel, sphere, piecewise-linear, 'math func', default)"],
              description="Density profile type per spatial dimension"),
    ParamSpec("den_min", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Minimum density for particle injection"),
    ParamSpec("density", "real(p_double)", float,
              default=1.0, constraints=["> 0"],
              description="Global density multiplier"),
    ParamSpec("num_x", "integer", int,
              default=-1,
              description="Number of points for piecewise-linear profile (-1 = auto)"),
    ParamSpec("x", "real(p_double)", float,
              dimensions=(100, "p_x_dim"), default=None,
              description="Piecewise-linear profile position values"),
    ParamSpec("fx", "real(p_double)", float,
              dimensions=(100, "p_x_dim"), default=0.0,
              description="Piecewise-linear profile density values"),
    ParamSpec("gauss_n_sigma", "integer", int,
              dimensions=("p_x_dim",), default=0,
              description="Number of sigmas to truncate Gaussian profile per dimension"),
    ParamSpec("gauss_range", "real(p_double)", float,
              dimensions=(2, "p_x_dim"), default=None,
              description="Gaussian profile range per dimension (lower, upper)"),
    ParamSpec("gauss_center", "real(p_double)", float,
              dimensions=("p_x_dim",), default=0.0,
              description="Gaussian profile center position per dimension"),
    ParamSpec("gauss_sigma", "real(p_double)", float,
              dimensions=("p_x_dim",), default=None,
              description="Gaussian profile sigma per dimension"),
    ParamSpec("channel_dir", "integer", int,
              default=1, constraints=[">= 1"],
              description="Channel profile direction (1-based spatial dimension)"),
    ParamSpec("channel_r0", "real(p_double)", float,
              default=None, constraints=["> 0"],
              description="Channel profile radius"),
    ParamSpec("channel_depth", "real(p_double)", float,
              default=None, constraints=[">= 0"],
              description="Channel profile depth"),
    ParamSpec("channel_size", "real(p_double)", float,
              default=None, constraints=["> 0"],
              description="Channel profile wall size"),
    ParamSpec("channel_center", "real(p_double)", float,
              dimensions=("p_x_dim",), default=None,
              description="Channel profile center position"),
    ParamSpec("channel_wall", "real(p_double)", float,
              default=0.0,
              description="Channel wall density"),
    ParamSpec("channel_pos", "real(p_double)", float,
              dimensions=(2,), default=None,
              description="Channel wall position (lower, upper)"),
    ParamSpec("channel_bottom", "real(p_double)", float,
              default=1.0,
              description="Channel bottom density"),
    ParamSpec("sphere_center", "real(p_double)", float,
              dimensions=("p_x_dim",), default=0.0,
              description="Spherical profile center position"),
    ParamSpec("sphere_radius", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Spherical profile radius"),
    ParamSpec("math_func_expr", "character(len=1024)", str,
              default="NO_FUNCTION_SUPPLIED!",
              description="Mathematical function expression for density profile"),
    ParamSpec("sample_rate", "integer", int,
              dimensions=(3,), default=32, constraints=[">= 1"],
              description="Sampling rate for constant-Q source"),
    # Beam-specific
    ParamSpec("focal_dist", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              condition="beam profile",
              description="Beam focal distance per momentum dimension"),
    ParamSpec("alpha", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              condition="beam profile",
              description="Beam angular divergence per momentum dimension"),
    ParamSpec("uth", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              condition="beam profile",
              description="Beam thermal momentum per dimension"),
    ParamSpec("gamma", "real(p_double)", float,
              default=1.0, constraints=[">= 1"],
              condition="beam profile",
              description="Beam relativistic gamma factor"),
    # File-specific
    ParamSpec("file_name", "character(len=256)", str,
              condition="file profile",
              description="File-based density profile path"),
    ParamSpec("x1_offset", "real(p_double)", float,
              default=0.0,
              condition="file profile",
              description="X1 offset for file-based profile"),
    ParamSpec("q_mult", "real(p_double)", float,
              default=1.0,
              condition="file profile",
              description="Charge multiplier for file-based profile"),
]

# ---- udist (spec/os-spec-udist.f03, namelist /nl_udist/) ----
_UDIST_PARAMS: list[ParamSpec] = [
    ParamSpec("uth_type", "character(len=20)", str,
              default="thermal",
              constraints=["in (none, thermal, 'random dir', waterbag, relmax, 'relmax boosted')"],
              description="Thermal momentum distribution type"),
    ParamSpec("use_spatial_uth", "logical", bool,
              default=False,
              description="Enable spatially varying thermal momentum"),
    ParamSpec("use_spatial_ufl", "logical", bool,
              default=False,
              description="Enable spatially varying fluid momentum"),
    ParamSpec("uth", "real(p_double)", float,
              dimensions=(3,), default=0.0, constraints=[">= 0"],
              description="Thermal momentum per dimension"),
    ParamSpec("ufl", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              description="Fluid momentum per dimension"),
    ParamSpec("spatial_uth", "character(len=1024)", str,
              dimensions=(3,), default="0",
              description="Mathematical expression for spatially varying thermal momentum"),
    ParamSpec("spatial_ufl", "character(len=1024)", str,
              dimensions=(3,), default="0",
              description="Mathematical expression for spatially varying fluid momentum"),
    ParamSpec("math_func_uth", "character(len=1024)", str,
              dimensions=(3,), default="0",
              description="Mathematical function for thermal momentum"),
    ParamSpec("relmax_T", "real(p_double)", float,
              default=0.0,
              condition="uth_type in (relmax, 'relmax boosted')",
              description="Temperature for relativistic Maxwellian distribution"),
    ParamSpec("relmax_umax", "real(p_double)", float,
              default=-1.0,
              condition="uth_type in (relmax, 'relmax boosted')",
              description="Maximum momentum for relativistic Maxwellian (-1 = auto)"),
    ParamSpec("use_classical_uadd", "logical", bool,
              default=False,
              description="Use classical (non-relativistic) momentum addition"),
    ParamSpec("use_particle_uacc", "logical", bool,
              default=False,
              description="Use particle acceleration in momentum distribution"),
    ParamSpec("n_accelerate", "integer", int,
              default=-1,
              description="Number of timesteps for particle acceleration"),
    ParamSpec("n_q_incr", "integer", int,
              default=-1,
              description="Number of timesteps for charge increment"),
    ParamSpec("n_accelerate_type", "character(len=20)", str,
              default="linear", constraints=["in (linear, regressive)"],
              description="Acceleration profile type"),
    ParamSpec("n_q_incr_type", "character(len=20)", str,
              default="linear", constraints=["in (linear, regressive)"],
              description="Charge increment profile type"),
    ParamSpec("umin", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              description="Minimum momentum for waterbag distribution"),
    ParamSpec("umax", "real(p_double)", float,
              dimensions=(3,), default=0.0,
              description="Maximum momentum for waterbag distribution"),
    ParamSpec("math_func_use_thermal", "logical", bool,
              dimensions=(3,), default=False,
              description="Use thermal distribution in math function"),
]

# ---- sdist (spec/os-spec-sdist.f03, namelist /nl_sdist/) ----
_SDIST_PARAMS: list[ParamSpec] = [
    ParamSpec("sdist_type", "character(len=20)", str,
              default="isotropic", constraints=["in (isotropic, 'fixed dir')"],
              condition="__HAS_SPIN__",
              description="Spin distribution type"),
    ParamSpec("sdir", "real(p_double)", float,
              dimensions=(32, 3), default=0.0,
              condition="__HAS_SPIN__",
              description="Spin direction vector"),
    ParamSpec("n_dirs", "integer", int,
              default=1, constraints=[">= 1"],
              condition="__HAS_SPIN__",
              description="Number of spin directions"),
    ParamSpec("pdf", "real(p_double)", float,
              dimensions=(32,), default=0.0,
              condition="__HAS_SPIN__",
              description="Probability density function for spin directions"),
    ParamSpec("gauss_mu", "real(p_double)", float,
              dimensions=(3,), default=None,
              condition="__HAS_SPIN__",
              description="Gaussian spin distribution mean"),
    ParamSpec("gauss_theta", "real(p_double)", float,
              default=0.0,
              condition="__HAS_SPIN__",
              description="Gaussian spin distribution angular divergence"),
]

# ---- spe_bound (spec/os-spec-boundary.f03, namelist /nl_spe_bound/) ----
_SPE_BOUND_PARAMS: list[ParamSpec] = [
    ParamSpec("type", "character(len=20)", str,
              dimensions=(2, "p_x_dim"), default="---",
              constraints=["in (absorbing, open, axial, specular, reflecting, thermal, periodic, ---)"],
              description="Particle species boundary condition type per dimension per wall"),
    ParamSpec("uth_bnd", "real(p_double)", float,
              dimensions=(3, 2, "p_x_dim"), default=0.0,
              description="Thermal boundary momentum per component/wall/dimension"),
    ParamSpec("ufl_bnd", "real(p_double)", float,
              dimensions=(3, 2, "p_x_dim"), default=0.0,
              description="Fluid boundary momentum per component/wall/dimension"),
    ParamSpec("thermal_type", "character(len=20)", str,
              dimensions=(2, 3), default="thermal",
              constraints=["in (thermal, 'half max', 'random dir', waterbag)"],
              description="Thermal boundary distribution type"),
]

# ---- piston (spec/os-spec-piston.f90, namelist /nl_piston/) ----
_PISTON_PARAMS: list[ParamSpec] = [
    ParamSpec("dim", "integer", int,
              default=1, constraints=[">= 1"],
              description="Piston direction (spatial dimension)"),
    ParamSpec("updown", "integer", int,
              default=1, constraints=["in (1, 2)"],
              description="Piston side: 1=up (lower wall), 2=down (upper wall)"),
    ParamSpec("v", "real(p_double)", float,
              default=0.0, constraints=["> 0"],
              description="Piston velocity"),
    ParamSpec("start_pos", "real(p_double)", float,
              default=0.0,
              description="Piston starting position"),
    ParamSpec("start_time", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Piston start time"),
    ParamSpec("stop_time", "real(p_double)", float,
              default=0.0,
              description="Piston stop time (must be > start_time)"),
    ParamSpec("opacity_factor", "real(p_double)", float,
              default=1.0, constraints=[">= 0"],
              description="Piston opacity factor"),
    ParamSpec("profile_type", "character(len=20)", str,
              default="uniform", constraints=["in (uniform, fparser)"],
              description="Piston profile type"),
    ParamSpec("profile_expression", "character(len=1024)", str,
              default="",
              condition="profile_type == 'fparser'",
              description="Mathematical expression for piston profile"),
]

# ---- diag_species (spec/diagnostics/os-spec-diagnostics.f03, namelist /nl_diag_species/) ----
_DIAG_SPECIES_PARAMS: list[ParamSpec] = [
    # Output frequencies
    ParamSpec("ndump_fac_pha", "integer", int,
              default=0, constraints=[">= 0"],
              description="Phase space output frequency (0 = disabled)"),
    ParamSpec("ndump_fac_pha_tavg", "integer", int,
              default=0, constraints=[">= 0"],
              description="Time-averaged phase space output frequency"),
    ParamSpec("ndump_fac_lineout", "integer", int,
              default=0, constraints=[">= 0"],
              description="Lineout diagnostic frequency"),
    ParamSpec("ndump_fac_ene", "integer", int,
              default=0, constraints=[">= 0"],
              description="Energy diagnostic output frequency"),
    ParamSpec("ndump_fac_heatflux", "integer", int,
              default=0, constraints=[">= 0"],
              description="Heat flux diagnostic output frequency"),
    ParamSpec("ndump_fac_temp", "integer", int,
              default=0, constraints=[">= 0"],
              description="Temperature diagnostic output frequency"),
    ParamSpec("ndump_fac_raw", "integer", int,
              default=0, constraints=[">= 0"],
              description="Raw particle data output frequency"),
    ParamSpec("ndump_fac", "integer", int,
              default=0, constraints=[">= 0"],
              description="Full report diagnostic output frequency"),
    ParamSpec("ndump_fac_ave", "integer", int,
              default=0, constraints=[">= 0"],
              description="Spatially averaged report diagnostic output frequency"),
    # Averaging / precision
    ParamSpec("n_ave", "integer", int,
              dimensions=(3,), default=0, constraints=[">= 0"],
              description="Number of spatial averages per dimension"),
    ParamSpec("prec", "integer", int,
              default=4,  # p_diag_prec = p_single
              description="Diagnostic output precision"),
    # Phase space axis ranges
    ParamSpec("ps_xmin", "real(p_single)", float,
              dimensions=("p_x_dim",), default=0.0,
              description="Phase space position axis lower bound"),
    ParamSpec("ps_xmax", "real(p_single)", float,
              dimensions=("p_x_dim",), default=0.0,
              description="Phase space position axis upper bound"),
    ParamSpec("ps_pmin", "real(p_single)", float,
              dimensions=(3,), default=0.0,
              description="Phase space momentum axis lower bound"),
    ParamSpec("ps_pmax", "real(p_single)", float,
              dimensions=(3,), default=0.0,
              description="Phase space momentum axis upper bound"),
    ParamSpec("ps_lmin", "real(p_single)", float,
              dimensions=(3,), default=0.0,
              description="Phase space angular momentum axis lower bound"),
    ParamSpec("ps_lmax", "real(p_single)", float,
              dimensions=(3,), default=0.0,
              description="Phase space angular momentum axis upper bound"),
    # Auto-range flags
    ParamSpec("if_ps_p_auto", "logical", bool,
              dimensions=(3,), default=False,
              description="Automatically compute momentum axis range"),
    ParamSpec("if_ps_l_auto", "logical", bool,
              dimensions=(3,), default=False,
              description="Automatically compute angular momentum axis range"),
    # 1D momentum phase space
    ParamSpec("ps_gammamin", "real(p_single)", float,
              default=1.0, constraints=[">= 1"],
              description="1D gamma/reduced-momentum axis lower bound"),
    ParamSpec("ps_gammamax", "real(p_single)", float,
              default=0.0,
              description="1D gamma axis upper bound (auto sets to +10)"),
    ParamSpec("if_ps_gamma_auto", "logical", bool,
              default=False,
              description="Automatically compute gamma axis range"),
    ParamSpec("ps_kemin", "real(p_single)", float,
              default=0.000001, constraints=["> 0"],
              description="1D kinetic energy axis lower bound"),
    ParamSpec("ps_kemax", "real(p_single)", float,
              default=0.0,
              description="1D kinetic energy axis upper bound (auto sets to +10)"),
    ParamSpec("if_ps_ke_auto", "logical", bool,
              default=False,
              description="Automatically compute kinetic energy axis range"),
    # Phase space resolution
    ParamSpec("ps_nx", "integer", int,
              dimensions=("p_x_dim",), default=64, constraints=[">= 2"],
              description="Phase space position axis resolution"),
    ParamSpec("ps_nx_3D", "integer", int,
              dimensions=("p_x_dim",), default=-1,
              description="3D phase space position resolution (-1 = use ps_nx)"),
    ParamSpec("ps_np", "integer", int,
              dimensions=(3,), default=64, constraints=[">= 2"],
              description="Phase space momentum axis resolution"),
    ParamSpec("ps_np_3D", "integer", int,
              dimensions=(3,), default=-1,
              description="3D phase space momentum resolution (-1 = use ps_np)"),
    ParamSpec("ps_nl", "integer", int,
              dimensions=(3,), default=64, constraints=[">= 2"],
              description="Phase space angular momentum axis resolution"),
    ParamSpec("ps_nl_3D", "integer", int,
              dimensions=(3,), default=-1,
              description="3D phase space angular momentum resolution (-1 = use ps_nl)"),
    ParamSpec("ps_ngamma", "integer", int,
              default=64, constraints=[">= 2"],
              description="1D gamma phase space resolution"),
    ParamSpec("ps_nke", "integer", int,
              default=64, constraints=[">= 2"],
              description="1D kinetic energy phase space resolution"),
    # Raw particle data
    ParamSpec("raw_gamma_limit", "real(p_single)", float,
              default=0.0, constraints=[">= 0"],
              description="Gamma threshold for raw particle data output"),
    ParamSpec("raw_fraction", "real(p_single)", float,
              default=1.0, constraints=["> 0"],
              description="Fraction of particles in raw output (0-1)"),
    ParamSpec("raw_math_expr", "character(len=1024)", str,
              default="",
              description="Mathematical expression filter for raw particle output"),
    ParamSpec("raw_if_pos_ref_box", "logical", bool,
              dimensions=("p_x_dim",), default=False,
              description="Reference raw particle positions to simulation box boundaries"),
    # Energy bins
    ParamSpec("n_ene_bins", "integer", int,
              default=0, constraints=[">= 0"],
              description="Number of energy bins (0 = disabled, max 32)"),
    ParamSpec("ene_bins", "real(p_single)", float,
              dimensions=(32,), default=0.0,
              description="Energy bin boundaries (in rest mass energy units)"),
    # Particle tracking
    ParamSpec("ndump_fac_tracks", "integer", int,
              default=0, constraints=[">= 0"],
              description="Particle tracking output frequency (0 = disabled)"),
    ParamSpec("n_start_tracks", "integer", int,
              default=-1,
              description="Iteration to start particle tracking (-1 = start immediately)"),
    ParamSpec("niter_tracks", "integer", int,
              default=1, constraints=[">= 1"],
              description="Number of iterations between track data writes"),
    ParamSpec("file_tags", "character(len=256)", str,
              default="",
              description="Particle tag file path (required when ndump_fac_tracks > 0)"),
    ParamSpec("ifdmp_tracks_efl", "logical", bool,
              dimensions=(3,), default=False,
              description="Track E-field components"),
    ParamSpec("ifdmp_tracks_bfl", "logical", bool,
              dimensions=(3,), default=False,
              description="Track B-field components"),
    ParamSpec("ifdmp_tracks_psi", "logical", bool,
              default=False,
              description="Track ponderomotive potential (psi)"),
    # Phase space and report lists
    ParamSpec("phasespaces", "character(len=32)", str,
              dimensions=(64,), default="-",
              description="List of phase space names to enable"),
    ParamSpec("pha_ene_bin", "character(len=32)", str,
              dimensions=(64,), default="-",
              description="List of energy-binned phase space names"),
    ParamSpec("pha_cell_avg", "character(len=32)", str,
              dimensions=(64,), default="-",
              description="List of cell-averaged phase space names"),
    ParamSpec("pha_time_avg", "character(len=32)", str,
              dimensions=(64,), default="-",
              description="List of time-averaged phase space names"),
    ParamSpec("n_tavg", "integer", int,
              default=0, constraints=[">= 0"],
              description="Number of timesteps to average for time-averaged output"),
    ParamSpec("reports", "character(len=32)", str,
              dimensions=(1024,), default="-",
              description="List of report quantity names to enable"),
    ParamSpec("rep_cell_avg", "character(len=32)", str,
              dimensions=(1024,), default="-",
              description="List of cell-averaged report quantity names"),
    ParamSpec("rep_udist", "character(len=32)", str,
              dimensions=(1024,), default="-",
              description="List of micro-distribution report quantity names"),
]

# ---- zpulse (zpulse/os-zpulse-std.f03, namelist /nl_zpulse/) ----
_ZPULSE_PARAMS: list[ParamSpec] = [
    ParamSpec("if_launch", "logical", bool,
              default=True,
              description="Enable laser pulse launch"),
    ParamSpec("b_type", "character(len=16)", str,
              default="normal", constraints=["in (normal, int)"],
              description="Laser field type (normal or integrated B-field)"),
    ParamSpec("a0", "real(p_double)", float,
              default=1.0, constraints=[">= 0"],
              description="Normalized laser amplitude"),
    ParamSpec("omega0", "real(p_double)", float,
              default=10.0, constraints=["> 0"],
              description="Laser frequency (normalized)"),
    ParamSpec("phase", "real(p_double)", float,
              default=0.0,
              description="Laser phase (degrees)"),
    ParamSpec("pol_type", "integer", int,
              default=0, constraints=["in (-1, 0, 1)"],
              description="Polarization type: -1=left circular, 0=linear, 1=right circular"),
    ParamSpec("pol", "real(p_double)", float,
              default=90.0,
              description="Polarization angle (degrees)"),
    ParamSpec("propagation", "character(len=16)", str,
              default="forward", constraints=["in (forward, backward)"],
              description="Pulse propagation direction"),
    ParamSpec("direction", "integer", int,
              default=1, constraints=[">= 1"],
              description="Propagation axis (1-based spatial dimension)"),
    ParamSpec("chirp_order", "integer", int,
              default=0, constraints=[">= 0"],
              description="Longitudinal chirp order (max 4)"),
    ParamSpec("chirp_coefs", "real(p_double)", float,
              dimensions=(4,), default=0.0,
              description="Longitudinal chirp coefficients"),
    ParamSpec("lon_fwhm", "real(p_double)", float,
              default=-1.0,
              description="Longitudinal full width at half maximum (overrides lon_rise/lon_fall if > 0)"),
    ParamSpec("lon_type", "character(len=16)", str,
              default="polynomial",
              constraints=["in (polynomial, sin2, gaussian, math, hermite)"],
              description="Longitudinal pulse envelope type"),
    ParamSpec("lon_start", "real(p_double)", float,
              default=None,
              description="Longitudinal pulse start position"),
    ParamSpec("lon_rise", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Longitudinal pulse rise time"),
    ParamSpec("lon_flat", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Longitudinal pulse flat-top duration"),
    ParamSpec("lon_fall", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Longitudinal pulse fall time"),
    ParamSpec("lon_duration", "real(p_double)", float,
              default=0.0,
              condition="lon_type == 'gaussian'",
              description="Longitudinal Gaussian pulse duration"),
    ParamSpec("lon_x0", "real(p_double)", float,
              default=None,
              description="Longitudinal pulse reference position"),
    ParamSpec("lon_range", "real(p_double)", float,
              default=None,
              description="Longitudinal pulse range"),
    ParamSpec("lon_math_func", "character(len=1024)", str,
              default="NO_FUNCTION_SUPPLIED!",
              condition="lon_type == 'math'",
              description="Mathematical function for longitudinal envelope"),
    ParamSpec("lon_tilt", "real(p_double)", float,
              dimensions=(2,), default=0.0,
              description="Longitudinal pulse tilt angle"),
    ParamSpec("per_type", "character(len=16)", str,
              default="plane",
              constraints=["in (plane, gaussian, hermite, laguerre)"],
              description="Transverse pulse profile type"),
    ParamSpec("per_center", "real(p_double)", float,
              dimensions=(2,), default=None,
              description="Transverse pulse center position"),
    ParamSpec("per_w0", "real(p_double)", float,
              dimensions=(2,), default=0.0, constraints=[">= 0"],
              description="Transverse pulse spot size"),
    ParamSpec("per_fwhm", "real(p_double)", float,
              dimensions=(2,), default=0.0, constraints=[">= 0"],
              description="Transverse pulse full width at half maximum (alternative to per_w0)"),
    ParamSpec("per_focus", "real(p_double)", float,
              dimensions=(2,), default=None,
              description="Transverse pulse focus position"),
    ParamSpec("per_chirp_order", "integer", int,
              default=0, constraints=[">= 0"],
              description="Transverse chirp order (max 4)"),
    ParamSpec("per_chirp_coefs", "real(p_double)", float,
              dimensions=(4,), default=0.0,
              description="Transverse chirp coefficients"),
    ParamSpec("per_w0_asym", "real(p_double)", float,
              dimensions=(2, 2), default=0.0,
              description="Asymmetric transverse spot size"),
    ParamSpec("per_fwhm_asym", "real(p_double)", float,
              dimensions=(2, 2), default=0.0,
              description="Asymmetric transverse full width at half maximum"),
    ParamSpec("per_focus_asym", "real(p_double)", float,
              dimensions=(2, 2), default=None,
              description="Asymmetric transverse focus position"),
    ParamSpec("per_asym_trans", "real(p_double)", float,
              dimensions=(2,), default=0.0,
              description="Asymmetric transverse translation"),
    ParamSpec("per_n", "integer", int,
              default=0, constraints=[">= 0"],
              description="Bessel/Laguerre mode order"),
    ParamSpec("per_0clip", "integer", int,
              default=1,
              description="Zero-clip transverse mode"),
    ParamSpec("per_kt", "real(p_double)", float,
              default=0.0,
              description="Transverse wavenumber"),
    ParamSpec("launch_time", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Pulse launch time"),
    ParamSpec("no_div_corr", "logical", bool,
              default=False,
              description="Disable divergence correction"),
    ParamSpec("per_tem_mode", "integer", int,
              dimensions=(2,), default=0, constraints=[">= 0"],
              description="Hermite-Gaussian TEM mode indices"),
]

# ---- zpulse_wall (zpulse/os-zpulse-wall.f03, namelist /nl_zpulse_wall/) ----
_ZPULSE_WALL_PARAMS: list[ParamSpec] = [
    ParamSpec("if_launch", "logical", bool,
              default=True,
              description="Enable laser pulse launch from wall"),
    ParamSpec("a0", "real(p_double)", float,
              default=1.0, constraints=[">= 0"],
              description="Normalized laser amplitude"),
    ParamSpec("omega0", "real(p_double)", float,
              default=10.0, constraints=["> 0"],
              description="Laser frequency (normalized)"),
    ParamSpec("phase", "real(p_double)", float,
              default=0.0,
              description="Laser phase (degrees)"),
    ParamSpec("pol_type", "integer", int,
              default=0, constraints=["in (-1, 0, 1)"],
              description="Polarization type: -1=left circular, 0=linear, 1=right circular"),
    ParamSpec("pol", "real(p_double)", float,
              default=90.0,
              description="Polarization angle (degrees)"),
    ParamSpec("propagation", "character(len=16)", str,
              default="forward", constraints=["in (forward, backward)"],
              description="Pulse propagation direction"),
    ParamSpec("direction", "integer", int,
              default=1, constraints=[">= 1"],
              description="Propagation axis (1-based spatial dimension)"),
    ParamSpec("chirp_order", "integer", int,
              default=0, constraints=[">= 0"],
              description="Chirp order (max 4)"),
    ParamSpec("chirp_coefs", "real(p_double)", float,
              dimensions=(4,), default=0.0,
              description="Chirp coefficients"),
    ParamSpec("tenv_fwhm", "real(p_double)", float,
              default=-1.0,
              description="Temporal full width at half maximum (overrides tenv_rise/tenv_fall if > 0)"),
    ParamSpec("tenv_type", "character(len=16)", str,
              default="polynomial",
              constraints=["in (polynomial, sin2, gaussian, math)"],
              description="Temporal envelope type"),
    ParamSpec("tenv_rise", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Temporal rise time"),
    ParamSpec("tenv_flat", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Temporal flat-top duration"),
    ParamSpec("tenv_fall", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Temporal fall time"),
    ParamSpec("tenv_duration", "real(p_double)", float,
              default=0.0,
              condition="tenv_type == 'gaussian'",
              description="Temporal Gaussian pulse duration"),
    ParamSpec("tenv_range", "real(p_double)", float,
              default=None,
              description="Temporal pulse range"),
    ParamSpec("tenv_math_func", "character(len=1024)", str,
              default="NO_FUNCTION_SUPPLIED!",
              condition="tenv_type == 'math'",
              description="Mathematical function for temporal envelope"),
    ParamSpec("tenv_tilt", "real(p_double)", float,
              dimensions=(2,), default=0.0,
              description="Temporal pulse tilt angle"),
    ParamSpec("per_type", "character(len=16)", str,
              default="plane",
              constraints=["in (plane, gaussian, hermite, laguerre)"],
              description="Transverse pulse profile type"),
    ParamSpec("per_center", "real(p_double)", float,
              dimensions=(2,), default=None,
              description="Transverse pulse center position"),
    ParamSpec("per_w0", "real(p_double)", float,
              dimensions=(2,), default=0.0, constraints=[">= 0"],
              description="Transverse pulse spot size"),
    ParamSpec("per_fwhm", "real(p_double)", float,
              dimensions=(2,), default=0.0, constraints=[">= 0"],
              description="Transverse pulse full width at half maximum"),
    ParamSpec("per_focus", "real(p_double)", float,
              dimensions=(2,), default=None,
              description="Transverse pulse focus position"),
    ParamSpec("per_chirp_order", "integer", int,
              default=0, constraints=[">= 0"],
              description="Transverse chirp order"),
    ParamSpec("per_chirp_coefs", "real(p_double)", float,
              dimensions=(4,), default=0.0,
              description="Transverse chirp coefficients"),
    ParamSpec("per_w0_asym", "real(p_double)", float,
              dimensions=(2, 2), default=0.0,
              description="Asymmetric transverse spot size"),
    ParamSpec("per_fwhm_asym", "real(p_double)", float,
              dimensions=(2, 2), default=0.0,
              description="Asymmetric transverse full width at half maximum"),
    ParamSpec("per_focus_asym", "real(p_double)", float,
              dimensions=(2, 2), default=None,
              description="Asymmetric transverse focus position"),
    ParamSpec("per_asym_trans", "real(p_double)", float,
              dimensions=(2,), default=0.0,
              description="Asymmetric transverse translation"),
    ParamSpec("per_n", "integer", int,
              default=0, constraints=[">= 0"],
              description="Bessel/Laguerre mode order"),
    ParamSpec("per_0clip", "integer", int,
              default=1,
              description="Zero-clip transverse mode"),
    ParamSpec("per_kt", "real(p_double)", float,
              default=0.0,
              description="Transverse wavenumber"),
    ParamSpec("per_tem_mode", "integer", int,
              dimensions=(2,), default=0, constraints=[">= 0"],
              description="Hermite-Gaussian TEM mode indices"),
    ParamSpec("launch_time", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Pulse launch time"),
]

# ---- zpulse_point (zpulse/os-zpulse-point.f03, namelist /nl_zpulse_point/) ----
_ZPULSE_POINT_PARAMS: list[ParamSpec] = [
    ParamSpec("if_launch", "logical", bool,
              default=True,
              description="Enable point-source laser pulse launch"),
    ParamSpec("a0", "real(p_double)", float,
              default=1.0, constraints=[">= 0"],
              description="Normalized laser amplitude"),
    ParamSpec("omega0", "real(p_double)", float,
              default=10.0, constraints=["> 0"],
              description="Laser frequency (normalized)"),
    ParamSpec("phase", "real(p_double)", float,
              default=0.0,
              description="Laser phase (degrees)"),
    ParamSpec("pol_vector", "real(p_double)", float,
              dimensions=(3,), default=None,  # default is (0, 0, 1)
              description="Polarization vector (3 components, must be non-zero)"),
    ParamSpec("chirp_order", "integer", int,
              default=0, constraints=[">= 0"],
              description="Chirp order (max 4)"),
    ParamSpec("chirp_coefs", "real(p_double)", float,
              dimensions=(4,), default=0.0,
              description="Chirp coefficients"),
    ParamSpec("tenv_type", "character(len=16)", str,
              default="polynomial",
              constraints=["in (polynomial, sin2, gaussian, math)"],
              description="Temporal envelope type"),
    ParamSpec("tenv_fwhm", "real(p_double)", float,
              default=-1.0,
              description="Temporal full width at half maximum (overrides tenv_rise/tenv_fall if > 0)"),
    ParamSpec("tenv_rise", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Temporal rise time"),
    ParamSpec("tenv_flat", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Temporal flat-top duration"),
    ParamSpec("tenv_fall", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Temporal fall time"),
    ParamSpec("tenv_duration", "real(p_double)", float,
              default=0.0,
              condition="tenv_type == 'gaussian'",
              description="Temporal Gaussian pulse duration"),
    ParamSpec("tenv_range", "real(p_double)", float,
              default=None,
              description="Temporal pulse range"),
    ParamSpec("tenv_math_func", "character(len=1024)", str,
              default="NO_FUNCTION_SUPPLIED!",
              condition="tenv_type == 'math'",
              description="Mathematical function for temporal envelope"),
    ParamSpec("launch_time", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Pulse launch time"),
    ParamSpec("point_pos", "real(p_double)", float,
              dimensions=("p_x_dim",), default=None,
              description="Point source position (required)"),
]

# ---- zpulse_speckle (zpulse/os-zpulse-speckle.f03, namelist /nl_zpulse_speckle/) ----
_ZPULSE_SPECKLE_PARAMS: list[ParamSpec] = [
    ParamSpec("if_launch", "logical", bool,
              default=True,
              description="Enable laser speckle pulse launch"),
    ParamSpec("a0", "real(p_double)", float,
              default=1.0, constraints=[">= 0"],
              description="Normalized laser amplitude"),
    ParamSpec("omega0", "real(p_double)", float,
              default=1.0, constraints=["> 0"],
              description="Laser frequency (normalized)"),
    ParamSpec("phase", "real(p_double)", float,
              default=0.0,
              description="Laser phase (degrees)"),
    ParamSpec("pol_type", "integer", int,
              default=0, constraints=["in (-1, 0, 1)"],
              description="Polarization type"),
    ParamSpec("pol", "real(p_double)", float,
              default=0.0,
              description="Polarization angle (degrees)"),
    ParamSpec("propagation", "character(len=16)", str,
              default="forward", constraints=["in (forward, backward)"],
              description="Pulse propagation direction"),
    ParamSpec("direction", "integer", int,
              default=1, constraints=[">= 1"],
              description="Propagation axis"),
    # Speckle-specific
    ParamSpec("speckle_type", "character(len=16)", str,
              default="default",
              constraints=["in (default, RPP, CPP, ISI, SSD, CPURP, file)"],
              description="Speckle pattern type"),
    ParamSpec("laser_bandwidth", "real(p_double)", float,
              dimensions=("per_ndim",), default=0.0,
              description="Laser bandwidth per transverse dimension"),
    ParamSpec("recurrence_time", "real(p_double)", float,
              default=None,
              description="Speckle recurrence time"),
    ParamSpec("duty_cycle", "real(p_double)", float,
              default=50.0, constraints=["> 0"],
              description="Speckle duty cycle (percent)"),
    ParamSpec("stud_duration", "real(p_double)", float,
              default=None,
              description="Stud pulse duration"),
    ParamSpec("stud_jitter", "real(p_double)", float,
              default=0.0,
              description="Stud pulse timing jitter"),
    ParamSpec("n_speckle", "integer", int,
              dimensions=("per_ndim",), default=1, constraints=[">= 1"],
              description="Number of speckles per transverse dimension"),
    ParamSpec("bandwidth_type", "character(len=16)", str,
              default="default",
              constraints=["in (default, gaussian, lorentzian, line)"],
              description="Bandwidth spectrum type"),
    ParamSpec("color_cycle", "integer", int,
              dimensions=("per_ndim",), default=1, constraints=[">= 1"],
              description="Number of color cycles per transverse dimension"),
    ParamSpec("nfm", "integer", int,
              dimensions=("per_ndim",), default=1, constraints=[">= 0"],
              description="Number of frequency modulation tones"),
    ParamSpec("fm", "real(p_double)", float,
              dimensions=(8, "per_ndim"), default=1.0,
              description="Frequency modulation tones"),
    ParamSpec("phasemod_amplitude", "real(p_double)", float,
              dimensions=(8, "per_ndim"), default=6.283185307179586,  # 2*PI
              description="Phase modulation amplitude"),
    ParamSpec("dt_update_speckle", "real(p_double)", float,
              default=None,
              description="Timestep interval for speckle pattern update"),
    ParamSpec("if_dump_speckle", "logical", bool,
              default=False,
              description="Output speckle pattern data"),
    ParamSpec("rseed_phase", "integer", int,
              default=23,
              description="Random seed for phase modulation"),
    ParamSpec("rseed_stud", "integer", int,
              default=71,
              description="Random seed for amplitude modulation"),
    ParamSpec("dt_update_pol", "real(p_double)", float,
              default=None,
              description="Timestep interval for polarization update"),
    ParamSpec("pol_stepping", "real(p_double)", float,
              default=90.0,
              description="Polarization stepping angle (degrees)"),
    # Temporal envelope
    ParamSpec("chirp_order", "integer", int,
              default=0, constraints=[">= 0"],
              description="Chirp order"),
    ParamSpec("chirp_coefs", "real(p_double)", float,
              dimensions=(4,), default=0.0,
              description="Chirp coefficients"),
    ParamSpec("chirp_period", "real(p_double)", float,
              default=None, constraints=["!= 0"],
              description="Chirp period"),
    ParamSpec("tenv_fwhm", "real(p_double)", float,
              default=-1.0,
              description="Temporal full width at half maximum"),
    ParamSpec("tenv_type", "character(len=16)", str,
              default="polynomial",
              constraints=["in (polynomial, sin2, gaussian, math)"],
              description="Temporal envelope type"),
    ParamSpec("tenv_rise", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Temporal rise time"),
    ParamSpec("tenv_flat", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Temporal flat-top duration"),
    ParamSpec("tenv_fall", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Temporal fall time"),
    ParamSpec("lon_focus", "real(p_double)", float,
              default=0.0,
              description="Longitudinal focus position"),
    ParamSpec("tenv_duration", "real(p_double)", float,
              default=0.0,
              condition="tenv_type == 'gaussian'",
              description="Temporal Gaussian pulse duration"),
    ParamSpec("tenv_range", "real(p_double)", float,
              default=None,
              description="Temporal pulse range"),
    ParamSpec("tenv_math_func", "character(len=1024)", str,
              default="NO_FUNCTION_SUPPLIED!",
              condition="tenv_type == 'math'",
              description="Mathematical function for temporal envelope"),
    ParamSpec("spatial_tilt", "real(p_double)", float,
              dimensions=(2,), default=0.0,
              description="Spatial tilt angle"),
    ParamSpec("per_center", "real(p_double)", float,
              dimensions=(2,), default=None,
              description="Transverse pulse center position"),
    ParamSpec("per_w0", "real(p_double)", float,
              dimensions=(2,), default=0.0, constraints=[">= 0"],
              description="Transverse pulse spot size"),
    ParamSpec("theta", "real(p_double)", float,
              dimensions=(2,), default=0.0,
              description="Speckle angular divergence"),
    ParamSpec("launch_time", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Pulse launch time"),
]

# ---- emf_solver (combined param set, namelist /nl_emf_solver/) ----
# Yee, Lehe, NDFX: no parameters (placeholder only). Fei/Custom: 16 params. Stencil: 2 params.
_EMF_SOLVER_PARAMS: list[ParamSpec] = [
    ParamSpec("type", "character(len=20)", str,
              default="standard",
              constraints=["in (standard, bump, xu, dual, customized-coef)"],
              condition="fei/custom solver",
              description="FEI solver type"),
    ParamSpec("n_coef", "integer", int,
              default=1, constraints=[">= 1"],
              condition="fei/custom solver",
              description="Number of field solver coefficients"),
    ParamSpec("coef_e", "real(p_double)", float,
              dimensions=("p_max_n_coef",), default=0.0,
              condition="fei/custom solver (dual, customized-coef)",
              description="E-field solver coefficients"),
    ParamSpec("coef_b", "real(p_double)", float,
              dimensions=("p_max_n_coef",), default=0.0,
              condition="fei/custom solver (dual, customized-coef)",
              description="B-field solver coefficients"),
    ParamSpec("solver_ord", "integer", int,
              default=2, constraints=[">= 2"],
              condition="fei/custom solver",
              description="Solver order (positive even integer)"),
    ParamSpec("kl", "real(p_double)", float,
              default=0.0,
              condition="fei/custom solver (bump type)",
              description="Lower wavenumber for bump solver"),
    ParamSpec("ku", "real(p_double)", float,
              default=0.0,
              condition="fei/custom solver (bump type)",
              description="Upper wavenumber for bump solver"),
    ParamSpec("dk", "real(p_double)", float,
              default=0.0,
              condition="fei/custom solver (bump type)",
              description="Wavenumber step for bump solver"),
    ParamSpec("filter_limit", "real(p_double)", float,
              default=1.0,
              condition="fei/custom solver",
              description="Filter limit for custom solver"),
    ParamSpec("filter_width", "real(p_double)", float,
              default=0.0,
              condition="fei/custom solver",
              description="Filter width for custom solver"),
    ParamSpec("correct_current", "logical", bool,
              default=False,
              condition="fei/custom solver",
              description="Enable current correction"),
    ParamSpec("filter_current", "logical", bool,
              default=False,
              condition="fei/custom solver",
              description="Enable current filtering"),
    ParamSpec("n_damp_cell", "integer", int,
              default=0, constraints=[">= 0"],
              condition="fei/custom solver",
              description="Number of damping grid cells"),
    ParamSpec("weight_w", "real(p_double)", float,
              default=None,  # huge(1.0) sentinel
              condition="fei/custom solver",
              description="Weight for wavenumber in filter"),
    ParamSpec("weight_n", "integer", int,
              default=10, constraints=[">= 1"],
              condition="fei/custom solver",
              description="Weight exponent for wavenumber in filter"),
    ParamSpec("taper_bnd", "logical", bool,
              default=False,
              condition="fei/custom solver",
              description="Enable boundary tapering"),
    ParamSpec("taper_order", "integer", int,
              default=2, constraints=[">= 1"],
              condition="fei/custom solver",
              description="Boundary taper order"),
    # Stencil solver parameters
    ParamSpec("k1", "real(p_double)", float,
              default=0.0, constraints=["<= 0"],
              condition="stencil solver",
              description="Stencil solver coefficient k1"),
    ParamSpec("k2", "real(p_double)", float,
              default=0.0,
              condition="stencil solver",
              description="Stencil solver coefficient k2"),
]

# ---- smooth (vdf/os-vdf-smooth.f90, namelist /nl_smooth/) ----
_SMOOTH_PARAMS: list[ParamSpec] = [
    ParamSpec("type", "character(len=20)", str,
              dimensions=("p_x_dim",), default="none",
              constraints=["in (none, gaussian, compensated, custom, digital, laserkdx)"],
              description="Smoothing/digital filter type per spatial dimension"),
    ParamSpec("order", "integer", int,
              dimensions=("p_x_dim",), default=0, constraints=[">= 0"],
              description="Filter order per spatial dimension"),
    ParamSpec("swfj", "real(p_double)", float,
              dimensions=(3, "p_order_max", "p_x_dim"), default=1.0,
              description="Custom filter weights"),
    ParamSpec("laserkdx_omega0", "real(p_double)", float,
              default=-1.0,
              condition="type == 'laserkdx'",
              description="Laser K-dispersion filter reference frequency"),
    ParamSpec("laserkdx_dir", "integer", int,
              default=1, constraints=[">= 1"],
              condition="type == 'laserkdx'",
              description="Laser K-dispersion filter direction"),
    ParamSpec("digital_A", "real(p_double)", float,
              dimensions=("p_x_dim",), default=None,
              condition="type == 'digital'",
              description="Digital filter amplitude"),
    ParamSpec("digital_fc", "real(p_double)", float,
              dimensions=("p_x_dim",), default=None,
              condition="type == 'digital'",
              description="Digital filter cutoff frequency"),
]

# ---- diag_emf (emf/diagnostics/os-emf-diag-define.f03, namelist /nl_diag_emf/) ----
_DIAG_EMF_PARAMS: list[ParamSpec] = [
    ParamSpec("ndump_fac", "integer", int,
              default=0, constraints=[">= 0"],
              description="EMF diagnostic output frequency (0 = disabled)"),
    ParamSpec("ndump_fac_ave", "integer", int,
              default=0, constraints=[">= 0"],
              description="Averaged EMF diagnostic output frequency"),
    ParamSpec("ndump_fac_lineout", "integer", int,
              default=0, constraints=[">= 0"],
              description="EMF lineout diagnostic frequency"),
    ParamSpec("ndump_fac_ene_int", "integer", int,
              default=0, constraints=[">= 0"],
              description="Integrated EM energy diagnostic output frequency"),
    ParamSpec("ndump_fac_charge_cons", "integer", int,
              default=0, constraints=[">= 0"],
              description="Charge conservation diagnostic output frequency"),
    ParamSpec("prec", "integer", int,
              default=4,  # p_single
              description="Diagnostic output precision"),
    ParamSpec("n_tavg", "integer", int,
              default=-1,
              description="Number of timesteps for time averaging"),
    ParamSpec("n_ave", "integer", int,
              dimensions=("p_x_dim",), default=-1,
              description="Number of spatial averages per dimension"),
    ParamSpec("reports", "character(len=32)", str,
              dimensions=(1024,), default="-",
              description="List of report quantity names"),
]

# ---- cathode (os-cathode.f03, namelist /nl_cathode/) ----
_CATHODE_PARAMS: list[ParamSpec] = [
    ParamSpec("dir", "integer", int,
              default=1, constraints=[">= 1"],
              description="Cathode injection direction (spatial dimension)"),
    ParamSpec("wall", "integer", int,
              default=1, constraints=["in (1, 2)"],
              description="Cathode wall side (1=lower, 2=upper)"),
    ParamSpec("t_start", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Cathode injection start time"),
    ParamSpec("t_rise", "real(p_double)", float,
              default=-1.0, constraints=[">= 0"],
              description="Cathode injection rise time"),
    ParamSpec("t_fall", "real(p_double)", float,
              default=-1.0, constraints=[">= 0"],
              description="Cathode injection fall time"),
    ParamSpec("t_flat", "real(p_double)", float,
              default=-1.0, constraints=[">= 0"],
              description="Cathode injection flat-top duration"),
    ParamSpec("mov_inj", "logical", bool,
              default=False,
              description="Enable moving window injection"),
    ParamSpec("prof_type", "character(len=16)", str,
              default="uniform",
              constraints=["in (uniform, gaussian, step, thruster)"],
              description="Cathode density profile type"),
    ParamSpec("density", "real(p_double)", float,
              default=1.0, constraints=[">= 0"],
              description="Cathode injection density multiplier"),
    ParamSpec("center", "real(p_double)", float,
              dimensions=(2,), default=None,
              description="Cathode beam center position"),
    ParamSpec("gauss_width", "real(p_double)", float,
              default=-1.0,
              condition="gaussian/step profile",
              description="Cathode Gaussian width"),
    ParamSpec("gauss_w0", "real(p_double)", float,
              default=-1.0,
              condition="gaussian profile",
              description="Cathode Gaussian spot size"),
    ParamSpec("channel_bottom", "real(p_double)", float,
              default=1.0,
              description="Cathode channel bottom density"),
    ParamSpec("channel_r0", "real(p_double)", float,
              default=None,
              description="Cathode channel radius"),
    ParamSpec("channel_depth", "real(p_double)", float,
              default=None,
              description="Cathode channel depth"),
    ParamSpec("channel_size", "real(p_double)", float,
              default=None,
              description="Cathode channel wall size"),
    ParamSpec("channel_wall", "real(p_double)", float,
              default=0.0,
              description="Cathode channel wall density"),
    ParamSpec("deposit_current", "logical", bool,
              default=True,
              description="Deposit current from cathode"),
    ParamSpec("den_min", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Minimum density for cathode injection"),
]

# ---- neutral (os-neutral.f03, namelist /nl_neutral/) ----
_NEUTRAL_PARAMS: list[ParamSpec] = [
    ParamSpec("name", "character(len=64)", str,
              description="Neutral gas species name"),
    ParamSpec("neutral_gas", "character(len=20)", str,
              default="H",
              constraints=["in (H, Li, Na, K, Rb, Cs, He, Ar, N, O, C, Ne, Xe, custom)"],
              description="Neutral gas type"),
    ParamSpec("ion_param", "real(p_double)", float,
              dimensions=(3, "p_ion_max"), default=0.0,
              condition="neutral_gas == 'custom'",
              description="Custom ionization rate parameters"),
    ParamSpec("den_min", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Minimum density for ionization"),
    ParamSpec("e_min", "real(p_double)", float,
              default=0.000001, constraints=[">= 0"],
              description="Minimum E-field magnitude for ionization"),
    ParamSpec("multi_max", "integer", int,
              default=None,  # p_ion_max
              description="Maximum ionization level"),
    ParamSpec("multi_min", "integer", int,
              default=0, constraints=[">= 0"],
              description="Minimum ionization level"),
    ParamSpec("if_tunnel", "logical", bool,
              default=True,
              description="Enable tunnel ionization"),
    ParamSpec("if_impact", "logical", bool,
              default=False,
              description="Enable impact ionization"),
    ParamSpec("inject_line", "logical", bool,
              default=True,
              description="Inject along field line"),
]

# ---- neutral_mov_ions (os-neutral.f03, namelist /nl_neutral_mov_ions/) ----
# Same parameters as neutral
_NEUTRAL_MOV_IONS_PARAMS: list[ParamSpec] = [
    ParamSpec("name", "character(len=64)", str,
              description="Neutral moving ion species name"),
    ParamSpec("neutral_gas", "character(len=20)", str,
              default="H",
              constraints=["in (H, Li, Na, K, Rb, Cs, He, Ar, N, O, C, Ne, Xe, custom)"],
              description="Neutral gas type"),
    ParamSpec("ion_param", "real(p_double)", float,
              dimensions=(3, "p_ion_max"), default=0.0,
              condition="neutral_gas == 'custom'",
              description="Custom ionization rate parameters"),
    ParamSpec("den_min", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Minimum density for ionization"),
    ParamSpec("e_min", "real(p_double)", float,
              default=0.000001, constraints=[">= 0"],
              description="Minimum E-field magnitude for ionization"),
    ParamSpec("multi_max", "integer", int,
              default=None,
              description="Maximum ionization level"),
    ParamSpec("multi_min", "integer", int,
              default=0, constraints=[">= 0"],
              description="Minimum ionization level"),
    ParamSpec("if_tunnel", "logical", bool,
              default=True,
              description="Enable tunnel ionization"),
    ParamSpec("if_impact", "logical", bool,
              default=False,
              description="Enable impact ionization"),
    ParamSpec("inject_line", "logical", bool,
              default=True,
              description="Inject along field line"),
]

# ---- num_ene (os-cross.f90, namelist /nl_num_ene/) ----
_NUM_ENE_PARAMS: list[ParamSpec] = [
    ParamSpec("num_ene", "integer", int,
              default=0, constraints=[">= 0"],
              condition="inside neutral with custom gas",
              description="Number of energy points for custom cross-sections"),
]

# ---- cross (os-cross.f90, namelist /nl_cross/) ----
_CROSS_PARAMS: list[ParamSpec] = [
    ParamSpec("cross", "real(p_double)", float,
              dimensions=("p_num_ene_max",), default=0.0,
              condition="inside neutral with custom gas",
              description="Cross-section data values [cm^-2]"),
    ParamSpec("ene", "real(p_double)", float,
              dimensions=("p_num_ene_max",), default=None,
              condition="inside neutral with custom gas",
              description="Energy data points [MeV]"),
]

# ---- diag_neutral (os-dneutral.f90, namelist /nl_diag_neutral/) ----
_DIAG_NEUTRAL_PARAMS: list[ParamSpec] = [
    ParamSpec("ndump_fac", "integer", int,
              default=0, constraints=[">= 0"],
              description="Neutral diagnostic output frequency (0 = disabled)"),
    ParamSpec("ndump_fac_ave", "integer", int,
              default=0, constraints=[">= 0"],
              description="Averaged neutral diagnostic output frequency"),
    ParamSpec("ndump_fac_lineout", "integer", int,
              default=0, constraints=[">= 0"],
              description="Neutral lineout diagnostic frequency"),
    ParamSpec("prec", "integer", int,
              default=4,  # p_single
              description="Diagnostic output precision"),
    ParamSpec("n_ave", "integer", int,
              dimensions=("p_x_dim",), default=1,
              description="Number of spatial averages per dimension"),
    ParamSpec("n_tavg", "integer", int,
              default=-1,
              description="Number of timesteps for time averaging"),
    ParamSpec("reports", "character(len=32)", str,
              dimensions=(1024,), default="-",
              description="List of report quantity names"),
]

# ---- collisions (spec/os-spec-collisions.f03, namelist /nl_collisions/) ----
_COLLISIONS_PARAMS: list[ParamSpec] = [
    ParamSpec("n_collide", "integer", int,
              default=0, constraints=[">= 0"],
              description="Number of collision pairs (0 = disabled)"),
    ParamSpec("nx_collision_cells", "integer", int,
              default=1, constraints=[">= 1"],
              description="Number of collision cells per sorting cell"),
    ParamSpec("coulomb_logarithm_automatic", "logical", bool,
              default=True,
              description="Use automatic Coulomb logarithm"),
    ParamSpec("coulomb_logarithm_value", "real(p_double)", float,
              default=0.0,
              description="Coulomb logarithm value (if not automatic)"),
    ParamSpec("collision_model", "character(len=32)", str,
              default="",
              constraints=["in (nanbu, sentoku, nanbu_rel, isotropic, takizuka, 'takizuka and abe', ta, 'non-rel', 'non-relativistic', perez, '')"],  # noqa: E501
              description="Collision model type (default: perez)"),
    ParamSpec("cross_section_correction", "character(len=32)", str,
              default="",
              constraints=["in (none, rejection, scattering, '')"],
              description="Cross-section correction method"),
    ParamSpec("timestep_cross_corr", "logical", bool,
              default=False,
              description="Enable timestep cross-correction"),
    ParamSpec("frame_correction", "character(len=32)", str,
              default="",
              constraints=["in (none, time, time_density, '')"],
              description="Frame correction method"),
    ParamSpec("root_finder", "character(len=32)", str,
              default="",
              description="Root-finding method for collision parameters"),
    ParamSpec("rng_seed", "integer", int,
              default=None,  # 1337*(mpi_node()+1) — dynamic default
              description="Random number generator seed for collisions"),
    ParamSpec("perez_low_temp_correction", "logical", bool,
              default=False,
              description="Enable Perez low-temperature correction"),
]

# ---- diag_current (current/os-current-diagnostics.f03, namelist /nl_diag_current/) ----
_DIAG_CURRENT_PARAMS: list[ParamSpec] = [
    ParamSpec("ndump_fac", "integer", int,
              default=0, constraints=[">= 0"],
              description="Current diagnostic output frequency (0 = disabled)"),
    ParamSpec("ndump_fac_ave", "integer", int,
              default=0, constraints=[">= 0"],
              description="Averaged current diagnostic output frequency"),
    ParamSpec("ndump_fac_lineout", "integer", int,
              default=0, constraints=[">= 0"],
              description="Current lineout diagnostic frequency"),
    ParamSpec("prec", "integer", int,
              default=4,  # p_single
              description="Diagnostic output precision"),
    ParamSpec("n_ave", "integer", int,
              dimensions=("p_x_dim",), default=-1,
              description="Number of spatial averages per dimension"),
    ParamSpec("n_tavg", "integer", int,
              default=-1,
              description="Number of timesteps for time averaging"),
    ParamSpec("reports", "character(len=32)", str,
              dimensions=(1024,), default="-",
              description="List of report quantity names"),
]

# ---- antenna_array (os-antenna_array.f03, namelist /nl_antenna_array/) ----
_ANTENNA_ARRAY_PARAMS: list[ParamSpec] = [
    ParamSpec("n_antenna", "integer", int,
              default=0, constraints=[">= 0"],
              description="Number of antennas (0 = disabled)"),
]

# ---- antenna (os-antenna.f03, namelist /nl_antenna/) ----
_ANTENNA_PARAMS: list[ParamSpec] = [
    ParamSpec("a0", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Normalized antenna amplitude"),
    ParamSpec("t_rise", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Antenna current rise time"),
    ParamSpec("t_flat", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Antenna current flat-top duration"),
    ParamSpec("t_fall", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Antenna current fall time"),
    ParamSpec("t_offset", "real(p_double)", float,
              default=0.0,
              description="Antenna current time offset"),
    ParamSpec("omega0", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Antenna frequency (normalized)"),
    ParamSpec("focus", "real(p_double)", float,
              default=0.0,
              description="Antenna focus position"),
    ParamSpec("x0", "real(p_double)", float,
              default=0.0,
              description="Antenna center x position"),
    ParamSpec("y0", "real(p_double)", float,
              default=0.0,
              description="Antenna center y position"),
    ParamSpec("rad_x", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Antenna x-direction spot size"),
    ParamSpec("rad_y", "real(p_double)", float,
              default=0.0, constraints=[">= 0"],
              description="Antenna y-direction spot size"),
    ParamSpec("ant_type", "integer", int,
              default=0,  # p_env_gaussian
              description="Antenna envelope type"),
    ParamSpec("pol", "real(p_double)", float,
              default=0.0,
              description="Polarization angle (degrees)"),
    ParamSpec("delay", "real(p_double)", float,
              default=0.0,
              description="Antenna time delay"),
    ParamSpec("side", "integer", int,
              default=1, constraints=["in (-1, 0, 1)"],
              description="Polarization handedness: -1=left circular, 0=linear, 1=right circular"),
    ParamSpec("tilt", "real(p_double)", float,
              default=0.0,
              description="Antenna tilt angle (degrees)"),
    ParamSpec("phase", "real(p_double)", float,
              default=0.0,
              description="Antenna phase (degrees)"),
    ParamSpec("direction", "integer", int,
              default=1, constraints=[">= 1"],
              description="Antenna propagation direction"),
    ParamSpec("chirp", "real(p_double)", float,
              default=0.0,
              description="Antenna chirp coefficient"),
    ParamSpec("jitterw", "real(p_double)", float,
              default=0.0,
              description="Frequency jitter magnitude"),
    ParamSpec("jitteromg", "real(p_double)", float,
              default=1.0,
              description="Frequency jitter omega"),
]

# ============================================================================
# Section -> parameter lookup
# ============================================================================

def _build_lookup() -> dict[str, list[ParamSpec]]:
    """Build section name -> parameter list lookup table."""
    return {
        "simulation": _SIMULATION_PARAMS,
        "node_conf": _NODE_CONF_PARAMS,
        "grid": _GRID_PARAMS,
        "time_step": _TIME_STEP_PARAMS,
        "restart": _RESTART_PARAMS,
        "space": _SPACE_PARAMS,
        "time": _TIME_PARAMS,
        "el_mag_fld": _EL_MAG_FLD_PARAMS,
        "emf_bound": _EMF_BOUND_PARAMS,
        "emf_solver": _EMF_SOLVER_PARAMS,
        "smooth": _SMOOTH_PARAMS,
        "diag_emf": _DIAG_EMF_PARAMS,
        "pgc": _PGC_PARAMS,
        "particles": _PARTICLES_PARAMS,
        "species": _SPECIES_PARAMS,
        "udist": _UDIST_PARAMS,
        "sdist": _SDIST_PARAMS,
        "profile": _PROFILE_PARAMS,
        "spe_bound": _SPE_BOUND_PARAMS,
        "piston": _PISTON_PARAMS,
        "diag_species": _DIAG_SPECIES_PARAMS,
        "cathode": _CATHODE_PARAMS,
        "neutral": _NEUTRAL_PARAMS,
        "neutral_mov_ions": _NEUTRAL_MOV_IONS_PARAMS,
        "num_ene": _NUM_ENE_PARAMS,
        "cross": _CROSS_PARAMS,
        "diag_neutral": _DIAG_NEUTRAL_PARAMS,
        "collisions": _COLLISIONS_PARAMS,
        "zpulse": _ZPULSE_PARAMS,
        "zpulse_wall": _ZPULSE_WALL_PARAMS,
        "zpulse_point": _ZPULSE_POINT_PARAMS,
        "zpulse_speckle": _ZPULSE_SPECKLE_PARAMS,
        "current": [],  # separator-only, no parameters
        "diag_current": _DIAG_CURRENT_PARAMS,
        "antenna_array": _ANTENNA_ARRAY_PARAMS,
        "antenna": _ANTENNA_PARAMS,
    }


_SECTION_PARAMS: dict[str, list[ParamSpec]] = _build_lookup()


def get_section_params(section_name: str) -> list[ParamSpec]:
    """Return the list of ParamSpec for a given section, or empty list if unknown."""
    return _SECTION_PARAMS.get(section_name, [])


def get_param_spec(section_name: str, param_name: str) -> ParamSpec | None:
    """Look up a ParamSpec by section and parameter name."""
    for ps in get_section_params(section_name):
        if ps.name == param_name:
            return ps
    return None


def is_known_param(section_name: str, param_name: str) -> bool:
    """Check whether a parameter name is known for the given section."""
    return get_param_spec(section_name, param_name) is not None
