"""Extract diagnostic quantity arrays from Fortran p_report_quants declarations.

Generates ``_generated/quantities.py`` — a mapping of diagnostic kind to
available quantity names.
"""

from __future__ import annotations

from pathlib import Path

_HEADER = '''"""Auto-generated diagnostic quantity lists from OSIRIS Fortran source.

Generated by: osiris-toolkit sync extract
DO NOT EDIT MANUALLY. Changes will be overwritten.
"""

from __future__ import annotations

# diagnostic_type -> list of quantity name strings
GEN_QUANTITIES: dict[str, list[str]] = {}
'''


def generate(output_path: str | Path, osiris_source_dir: str | Path) -> None:
    """Scan Fortran source and write _generated/quantities.py."""
    from osiris_toolkit.sync.extractor import FortranScanner

    scanner = FortranScanner(osiris_source_dir)
    scanner.scan()

    # Group quantities by diagnostic type
    kinds: dict[str, list[str]] = {}

    for entry in scanner.quantities:
        array_name = entry.array_name
        if array_name in ("p_rep_udist",):
            kinds["UDIST"] = entry.quantities
        elif "emf-diag-define" in entry.file_path.lower():
            kinds["EMF"] = entry.quantities
        elif "os-current-diagnostics" in entry.file_path.lower():
            kinds["CURRENT"] = entry.quantities
        elif "os-spec-diagnostics" in entry.file_path.lower() and array_name == "p_report_quants":
            kinds["DENSITY"] = entry.quantities
        elif "os-particles-define" in entry.file_path.lower():
            kinds["CHARGE"] = entry.quantities
        elif "os-dneutral" in entry.file_path.lower():
            kinds["NEUTRAL"] = entry.quantities
        elif "os-emf-meta" in entry.file_path.lower():
            kinds["META_EMF"] = entry.quantities

    # Build output
    lines: list[str] = [_HEADER]

    for kind_name in sorted(kinds):
        quants = kinds[kind_name]
        lines.append(f"# {kind_name}: {len(quants)} quantities")
        lines.append(f"GEN_QUANTITIES[{kind_name!r}] = [")
        for q in quants:
            lines.append(f"    {q!r},")
        lines.append("]")
        lines.append("")

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
