"""Extract parameter definitions from Fortran namelist declarations.

Generates ``_generated/parameters.py`` — a mapping of section name to
parameter list with Fortran types and default values.
"""

from __future__ import annotations

import re
from pathlib import Path

from osiris_toolkit.sync.extractor import (
    FORTRAN_TO_PYTHON,
    FortranScanner,
    NamelistVar,
)

_HEADER = '''"""Auto-generated parameter definitions from OSIRIS Fortran source.

Generated by: osiris-toolkit sync extract
DO NOT EDIT MANUALLY. Changes will be overwritten.

Each parameter has:
    name         — Fortran variable name
    fortran_type — original Fortran type declaration
    python_type  — corresponding Python type
    default      — default value from Fortran source (None if not found)
    description  — human-readable description from reference docs (empty if unavailable)
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class _GenParam:
    """One auto-generated parameter definition."""
    name: str
    fortran_type: str = ""
    python_type: str = "float"
    default: str | None = None
    description: str = ""


# section_name -> {param_name -> _GenParam}
GEN_PARAMETERS: dict[str, dict[str, _GenParam]] = {}
'''


def _type_to_python(ftype: str) -> str:
    """Map Fortran type string to Python type name."""
    ftype_lower = ftype.lower().strip()
    for f_key, py_type in FORTRAN_TO_PYTHON.items():
        if ftype_lower.startswith(f_key):
            return py_type
    if "character" in ftype_lower:
        return "str"
    if "integer" in ftype_lower:
        return "int"
    if "real" in ftype_lower:
        return "float"
    if "logical" in ftype_lower:
        return "bool"
    return "float"


def _clean_default(raw: str | None) -> str | None:
    """Clean a Fortran default value for Python output."""
    if raw is None:
        return None
    cleaned = raw.strip().rstrip(",")
    # Convert Fortran boolean notation
    if cleaned.lower() in (".true.", ".false."):
        return cleaned.strip(".").capitalize()
    # Remove Fortran type suffixes: _p_double, _p_k_fld, etc.
    cleaned = re.sub(r"_\w+$", "", cleaned)
    # Remove Fortran exponent D → E
    cleaned = cleaned.replace("D", "e").replace("d", "e")
    # Handle huge() calls
    cleaned = cleaned.replace("huge(1.0)", "None  # huge")
    cleaned = cleaned.replace("huge(1.0_p_double)", "None  # huge")
    # Handle function calls
    if "(" in cleaned:
        return f"None  # was: {cleaned}"
    return cleaned


def generate(
    output_path: str | Path,
    osiris_source_dir: str | Path,
    docs_path: str | Path | None = None,
) -> None:
    """Scan Fortran source and write _generated/parameters.py.

    If *docs_path* is provided, parameter descriptions are extracted from
    the OSIRIS reference documentation (docs/reference/*.md) and injected
    into the generated output.
    """
    scanner = FortranScanner(osiris_source_dir)
    scanner.scan()

    # Load descriptions from docs if available
    descriptions: dict[str, dict[str, str]] = {}
    if docs_path is not None:
        from osiris_toolkit.sync.descriptions import parse_docs

        descriptions = parse_docs(docs_path)

    # Organize parameters by section
    sections: dict[str, dict[str, NamelistVar]] = {}
    for entry in scanner.namelists:
        sec_name = entry.section_name
        if sec_name not in sections:
            sections[sec_name] = {}
        for var in entry.variables:
            if var.name not in sections[sec_name]:
                sections[sec_name][var.name] = var

    # Generate output
    lines: list[str] = [_HEADER]

    for sec_name in sorted(sections):
        params = sections[sec_name]
        sec_descs = descriptions.get(sec_name, {})
        lines.append(f"# -- {sec_name} ({len(params)} parameters)")
        lines.append(f"_sec_{sec_name} = {{}}")
        for pname in sorted(params):
            var = params[pname]
            py_type = _type_to_python(var.fortran_type) if var.fortran_type else "float"
            default = _clean_default(var.default)
            default_str = repr(default) if default is not None else "None"
            desc = sec_descs.get(pname.lower(), "")
            lines.append(
                f"_sec_{sec_name}[{pname!r}] = _GenParam("
            )
            lines.append(f"    name={pname!r},")
            lines.append(f"    fortran_type={var.fortran_type!r},")
            lines.append(f"    python_type={py_type!r},")
            lines.append(f"    default={default_str},")
            lines.append(f"    description={desc!r},")
            lines.append(")")
        lines.append(f"GEN_PARAMETERS[{sec_name!r}] = _sec_{sec_name}")
        lines.append("")

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
