"""Extract section-to-namelist mapping from get_namelist calls.

Generates ``_generated/sections.py`` — a list of all input sections
found in the Fortran source.
"""

from __future__ import annotations

from pathlib import Path

_HEADER = '''"""Auto-generated section list from OSIRIS Fortran get_namelist calls.

Generated by: osiris-toolkit sync extract
DO NOT EDIT MANUALLY. Changes will be overwritten.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class _GenSection:
    """One auto-generated section entry."""
    name: str          # section name (without nl_ prefix)
    nl_name: str       # full namelist name (with nl_ prefix)


# All sections found in Fortran source
GEN_SECTIONS: list[_GenSection] = []
'''


def generate(output_path: str | Path, osiris_source_dir: str | Path) -> None:
    """Scan Fortran source and write _generated/sections.py."""
    from osiris_toolkit.sync.extractor import FortranScanner

    scanner = FortranScanner(osiris_source_dir)
    scanner.scan()

    # Build ordered section list
    seen: set[str] = set()
    sections: list[tuple[str, str]] = []

    for entry in scanner.sections:
        # Skip empty or malformed entries
        if not entry.section_name or entry.section_nl in ("nl_",):
            continue
        if entry.section_name not in seen:
            seen.add(entry.section_name)
            sections.append((entry.section_name, entry.section_nl))

    lines: list[str] = [_HEADER]

    for sec_name, nl_name in sorted(sections):
        lines.append(
            f"GEN_SECTIONS.append(_GenSection(name={sec_name!r}, nl_name={nl_name!r}))"
        )
    lines.append("")

    # Also output the canonical section order if we can determine it
    # from os-main.f03 read_input sequence
    lines.append("# Section names only (for quick reference)")
    lines.append("SECTION_NAMES: list[str] = [")
    for sec_name, _ in sections:
        lines.append(f"    {sec_name!r},")
    lines.append("]")
    lines.append("")

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
