"""Auto-generated parameter definitions from OSIRIS Fortran source.

Generated by: osiris-toolkit sync extract
DO NOT EDIT MANUALLY. Changes will be overwritten.

Each parameter has:
    name         — Fortran variable name
    fortran_type — original Fortran type declaration
    python_type  — corresponding Python type
    default      — default value from Fortran source (None if not found)
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class _GenParam:
    """One auto-generated parameter definition."""
    name: str
    fortran_type: str = ""
    python_type: str = "float"
    default: str | None = None


# section_name -> {param_name -> _GenParam}
GEN_PARAMETERS: dict[str, dict[str, _GenParam]] = {}

# -- antenna (21 parameters)
_sec_antenna = {}
_sec_antenna['a0'] = _GenParam(
    name='a0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['ant_type'] = _GenParam(
    name='ant_type',
    fortran_type='integer',
    python_type='int',
    default='p',
)
_sec_antenna['chirp'] = _GenParam(
    name='chirp',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['delay'] = _GenParam(
    name='delay',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['direction'] = _GenParam(
    name='direction',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_antenna['focus'] = _GenParam(
    name='focus',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['jitteromg'] = _GenParam(
    name='jitteromg',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='1.0',
)
_sec_antenna['jitterw'] = _GenParam(
    name='jitterw',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['omega0'] = _GenParam(
    name='omega0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['phase'] = _GenParam(
    name='phase',
    fortran_type='real (p_k_fld)',
    python_type='float',
    default='this%omega0*local_time+this%phase',
)
_sec_antenna['pol'] = _GenParam(
    name='pol',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['rad_x'] = _GenParam(
    name='rad_x',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['rad_y'] = _GenParam(
    name='rad_y',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['side'] = _GenParam(
    name='side',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_antenna['t_fall'] = _GenParam(
    name='t_fall',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['t_flat'] = _GenParam(
    name='t_flat',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['t_offset'] = _GenParam(
    name='t_offset',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['t_rise'] = _GenParam(
    name='t_rise',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['tilt'] = _GenParam(
    name='tilt',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['x0'] = _GenParam(
    name='x0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_antenna['y0'] = _GenParam(
    name='y0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
GEN_PARAMETERS['antenna'] = _sec_antenna

# -- antenna_array (1 parameters)
_sec_antenna_array = {}
_sec_antenna_array['n_antenna'] = _GenParam(
    name='n_antenna',
    fortran_type='integer',
    python_type='int',
    default='0',
)
GEN_PARAMETERS['antenna_array'] = _sec_antenna_array

# -- cathode (19 parameters)
_sec_cathode = {}
_sec_cathode['center'] = _GenParam(
    name='center',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_cathode['channel_bottom'] = _GenParam(
    name='channel_bottom',
    fortran_type='real(p_double)',
    python_type='float',
    default='1.0',
)
_sec_cathode['channel_depth'] = _GenParam(
    name='channel_depth',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge( 1.0_p_eouble )',
)
_sec_cathode['channel_r0'] = _GenParam(
    name='channel_r0',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge( 1.0_p_eouble )',
)
_sec_cathode['channel_size'] = _GenParam(
    name='channel_size',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge( 1.0_p_eouble )',
)
_sec_cathode['channel_wall'] = _GenParam(
    name='channel_wall',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_cathode['den_min'] = _GenParam(
    name='den_min',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_cathode['density'] = _GenParam(
    name='density',
    fortran_type='',
    python_type='float',
    default='1.0',
)
_sec_cathode['deposit_current'] = _GenParam(
    name='deposit_current',
    fortran_type='logical',
    python_type='bool',
    default='True',
)
_sec_cathode['dir'] = _GenParam(
    name='dir',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_cathode['gauss_w0'] = _GenParam(
    name='gauss_w0',
    fortran_type='',
    python_type='float',
    default='-1.0',
)
_sec_cathode['gauss_width'] = _GenParam(
    name='gauss_width',
    fortran_type='',
    python_type='float',
    default='-1.0',
)
_sec_cathode['mov_inj'] = _GenParam(
    name='mov_inj',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_cathode['prof_type'] = _GenParam(
    name='prof_type',
    fortran_type='',
    python_type='float',
    default='"uniform"',
)
_sec_cathode['t_fall'] = _GenParam(
    name='t_fall',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1.0',
)
_sec_cathode['t_flat'] = _GenParam(
    name='t_flat',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1.0',
)
_sec_cathode['t_rise'] = _GenParam(
    name='t_rise',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1.0',
)
_sec_cathode['t_start'] = _GenParam(
    name='t_start',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_cathode['wall'] = _GenParam(
    name='wall',
    fortran_type='integer',
    python_type='int',
    default='1',
)
GEN_PARAMETERS['cathode'] = _sec_cathode

# -- collisions (11 parameters)
_sec_collisions = {}
_sec_collisions['collision_model'] = _GenParam(
    name='collision_model',
    fortran_type='character( len = p_LongestName )',
    python_type='str',
    default='""',
)
_sec_collisions['coulomb_logarithm_automatic'] = _GenParam(
    name='coulomb_logarithm_automatic',
    fortran_type='logical',
    python_type='bool',
    default='True',
)
_sec_collisions['coulomb_logarithm_value'] = _GenParam(
    name='coulomb_logarithm_value',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0.0',
)
_sec_collisions['cross_section_correction'] = _GenParam(
    name='cross_section_correction',
    fortran_type='character( len = p_LongestName )',
    python_type='str',
    default='""',
)
_sec_collisions['frame_correction'] = _GenParam(
    name='frame_correction',
    fortran_type='character( len = p_LongestName )',
    python_type='str',
    default='""',
)
_sec_collisions['n_collide'] = _GenParam(
    name='n_collide',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_collisions['nx_collision_cells'] = _GenParam(
    name='nx_collision_cells',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_collisions['perez_low_temp_correction'] = _GenParam(
    name='perez_low_temp_correction',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_collisions['rng_seed'] = _GenParam(
    name='rng_seed',
    fortran_type='integer',
    python_type='int',
    default='None  # was: 1337*(mpi_noee()+1)',
)
_sec_collisions['root_finder'] = _GenParam(
    name='root_finder',
    fortran_type='character( len = p_LongestName )',
    python_type='str',
    default='""',
)
_sec_collisions['timestep_cross_corr'] = _GenParam(
    name='timestep_cross_corr',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
GEN_PARAMETERS['collisions'] = _sec_collisions

# -- cross (2 parameters)
_sec_cross = {}
_sec_cross['cross'] = _GenParam(
    name='cross',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_cross['ene'] = _GenParam(
    name='ene',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='None  # was: - huge( 1.0_p_k_fle )',
)
GEN_PARAMETERS['cross'] = _sec_cross

# -- diag_current (7 parameters)
_sec_diag_current = {}
_sec_diag_current['n_ave'] = _GenParam(
    name='n_ave',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_diag_current['n_tavg'] = _GenParam(
    name='n_tavg',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_diag_current['ndump_fac'] = _GenParam(
    name='ndump_fac',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_current['ndump_fac_ave'] = _GenParam(
    name='ndump_fac_ave',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_current['ndump_fac_lineout'] = _GenParam(
    name='ndump_fac_lineout',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_current['prec'] = _GenParam(
    name='prec',
    fortran_type='integer',
    python_type='int',
    default='p',
)
_sec_diag_current['reports'] = _GenParam(
    name='reports',
    fortran_type='character( len = p_max_reports_len )',
    python_type='str',
    default='"-"',
)
GEN_PARAMETERS['diag_current'] = _sec_diag_current

# -- diag_emf (9 parameters)
_sec_diag_emf = {}
_sec_diag_emf['n_ave'] = _GenParam(
    name='n_ave',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_diag_emf['n_tavg'] = _GenParam(
    name='n_tavg',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_diag_emf['ndump_fac'] = _GenParam(
    name='ndump_fac',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_emf['ndump_fac_ave'] = _GenParam(
    name='ndump_fac_ave',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_emf['ndump_fac_charge_cons'] = _GenParam(
    name='ndump_fac_charge_cons',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_emf['ndump_fac_ene_int'] = _GenParam(
    name='ndump_fac_ene_int',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_emf['ndump_fac_lineout'] = _GenParam(
    name='ndump_fac_lineout',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_emf['prec'] = _GenParam(
    name='prec',
    fortran_type='integer',
    python_type='int',
    default='p',
)
_sec_diag_emf['reports'] = _GenParam(
    name='reports',
    fortran_type='character( len = p_max_reports_len )',
    python_type='str',
    default='"-"',
)
GEN_PARAMETERS['diag_emf'] = _sec_diag_emf

# -- diag_neutral (7 parameters)
_sec_diag_neutral = {}
_sec_diag_neutral['n_ave'] = _GenParam(
    name='n_ave',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_diag_neutral['n_tavg'] = _GenParam(
    name='n_tavg',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_diag_neutral['ndump_fac'] = _GenParam(
    name='ndump_fac',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_neutral['ndump_fac_ave'] = _GenParam(
    name='ndump_fac_ave',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_neutral['ndump_fac_lineout'] = _GenParam(
    name='ndump_fac_lineout',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_neutral['prec'] = _GenParam(
    name='prec',
    fortran_type='integer',
    python_type='int',
    default='p',
)
_sec_diag_neutral['reports'] = _GenParam(
    name='reports',
    fortran_type='character( len = p_max_reports_len )',
    python_type='str',
    default='"-"',
)
GEN_PARAMETERS['diag_neutral'] = _sec_diag_neutral

# -- diag_species (54 parameters)
_sec_diag_species = {}
_sec_diag_species['ene_bins'] = _GenParam(
    name='ene_bins',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0',
)
_sec_diag_species['file_tags'] = _GenParam(
    name='file_tags',
    fortran_type='character(len = p_max_filename_len)',
    python_type='str',
    default="''",
)
_sec_diag_species['if_ps_gamma_auto'] = _GenParam(
    name='if_ps_gamma_auto',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_diag_species['if_ps_ke_auto'] = _GenParam(
    name='if_ps_ke_auto',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_diag_species['if_ps_l_auto'] = _GenParam(
    name='if_ps_l_auto',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_diag_species['if_ps_p_auto'] = _GenParam(
    name='if_ps_p_auto',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_diag_species['ifdmp_tracks_bfl'] = _GenParam(
    name='ifdmp_tracks_bfl',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_diag_species['ifdmp_tracks_efl'] = _GenParam(
    name='ifdmp_tracks_efl',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_diag_species['ifdmp_tracks_psi'] = _GenParam(
    name='ifdmp_tracks_psi',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_diag_species['n_ave'] = _GenParam(
    name='n_ave',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_species['n_ene_bins'] = _GenParam(
    name='n_ene_bins',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_species['n_start_tracks'] = _GenParam(
    name='n_start_tracks',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_diag_species['n_tavg'] = _GenParam(
    name='n_tavg',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_species['ndump_fac'] = _GenParam(
    name='ndump_fac',
    fortran_type='',
    python_type='float',
    default='0',
)
_sec_diag_species['ndump_fac_ave'] = _GenParam(
    name='ndump_fac_ave',
    fortran_type='',
    python_type='float',
    default='0',
)
_sec_diag_species['ndump_fac_ene'] = _GenParam(
    name='ndump_fac_ene',
    fortran_type='',
    python_type='float',
    default='0',
)
_sec_diag_species['ndump_fac_heatflux'] = _GenParam(
    name='ndump_fac_heatflux',
    fortran_type='',
    python_type='float',
    default='0',
)
_sec_diag_species['ndump_fac_lineout'] = _GenParam(
    name='ndump_fac_lineout',
    fortran_type='',
    python_type='float',
    default='0',
)
_sec_diag_species['ndump_fac_pha'] = _GenParam(
    name='ndump_fac_pha',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_species['ndump_fac_pha_tavg'] = _GenParam(
    name='ndump_fac_pha_tavg',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_species['ndump_fac_raw'] = _GenParam(
    name='ndump_fac_raw',
    fortran_type='',
    python_type='float',
    default='0',
)
_sec_diag_species['ndump_fac_temp'] = _GenParam(
    name='ndump_fac_temp',
    fortran_type='',
    python_type='float',
    default='0',
)
_sec_diag_species['ndump_fac_tracks'] = _GenParam(
    name='ndump_fac_tracks',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_diag_species['niter_tracks'] = _GenParam(
    name='niter_tracks',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_diag_species['pha_cell_avg'] = _GenParam(
    name='pha_cell_avg',
    fortran_type='',
    python_type='float',
    default='"-"',
)
_sec_diag_species['pha_ene_bin'] = _GenParam(
    name='pha_ene_bin',
    fortran_type='',
    python_type='float',
    default='"-"',
)
_sec_diag_species['pha_time_avg'] = _GenParam(
    name='pha_time_avg',
    fortran_type='',
    python_type='float',
    default='"-"',
)
_sec_diag_species['phasespaces'] = _GenParam(
    name='phasespaces',
    fortran_type='',
    python_type='float',
    default='"-"',
)
_sec_diag_species['prec'] = _GenParam(
    name='prec',
    fortran_type='integer',
    python_type='int',
    default='p',
)
_sec_diag_species['ps_gammamax'] = _GenParam(
    name='ps_gammamax',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0',
)
_sec_diag_species['ps_gammamin'] = _GenParam(
    name='ps_gammamin',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='1.0',
)
_sec_diag_species['ps_kemax'] = _GenParam(
    name='ps_kemax',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0',
)
_sec_diag_species['ps_kemin'] = _GenParam(
    name='ps_kemin',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0.000001',
)
_sec_diag_species['ps_lmax'] = _GenParam(
    name='ps_lmax',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0',
)
_sec_diag_species['ps_lmin'] = _GenParam(
    name='ps_lmin',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0',
)
_sec_diag_species['ps_ngamma'] = _GenParam(
    name='ps_ngamma',
    fortran_type='integer',
    python_type='int',
    default='64',
)
_sec_diag_species['ps_nke'] = _GenParam(
    name='ps_nke',
    fortran_type='integer',
    python_type='int',
    default='64',
)
_sec_diag_species['ps_nl'] = _GenParam(
    name='ps_nl',
    fortran_type='integer',
    python_type='int',
    default='64',
)
_sec_diag_species['ps_nl_3D'] = _GenParam(
    name='ps_nl_3D',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_diag_species['ps_np'] = _GenParam(
    name='ps_np',
    fortran_type='integer',
    python_type='int',
    default='64',
)
_sec_diag_species['ps_np_3D'] = _GenParam(
    name='ps_np_3D',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_diag_species['ps_nx'] = _GenParam(
    name='ps_nx',
    fortran_type='integer',
    python_type='int',
    default='64',
)
_sec_diag_species['ps_nx_3D'] = _GenParam(
    name='ps_nx_3D',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_diag_species['ps_pmax'] = _GenParam(
    name='ps_pmax',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0',
)
_sec_diag_species['ps_pmin'] = _GenParam(
    name='ps_pmin',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0',
)
_sec_diag_species['ps_xmax'] = _GenParam(
    name='ps_xmax',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0',
)
_sec_diag_species['ps_xmin'] = _GenParam(
    name='ps_xmin',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0',
)
_sec_diag_species['raw_fraction'] = _GenParam(
    name='raw_fraction',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='1.0',
)
_sec_diag_species['raw_gamma_limit'] = _GenParam(
    name='raw_gamma_limit',
    fortran_type='real(p_diag_prec)',
    python_type='float',
    default='0',
)
_sec_diag_species['raw_if_pos_ref_box'] = _GenParam(
    name='raw_if_pos_ref_box',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_diag_species['raw_math_expr'] = _GenParam(
    name='raw_math_expr',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default="''",
)
_sec_diag_species['rep_cell_avg'] = _GenParam(
    name='rep_cell_avg',
    fortran_type='',
    python_type='float',
    default='"-"',
)
_sec_diag_species['rep_udist'] = _GenParam(
    name='rep_udist',
    fortran_type='',
    python_type='float',
    default='"-"',
)
_sec_diag_species['reports'] = _GenParam(
    name='reports',
    fortran_type='',
    python_type='float',
    default='"-"',
)
GEN_PARAMETERS['diag_species'] = _sec_diag_species

# -- el_mag_fld (29 parameters)
_sec_el_mag_fld = {}
_sec_el_mag_fld['ext_b0'] = _GenParam(
    name='ext_b0',
    fortran_type='',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['ext_b_mfunc'] = _GenParam(
    name='ext_b_mfunc',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default='"NO',
)
_sec_el_mag_fld['ext_dipole_b_m'] = _GenParam(
    name='ext_dipole_b_m',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['ext_dipole_b_r0'] = _GenParam(
    name='ext_dipole_b_r0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.001',
)
_sec_el_mag_fld['ext_dipole_b_x0'] = _GenParam(
    name='ext_dipole_b_x0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['ext_dipole_e_p'] = _GenParam(
    name='ext_dipole_e_p',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['ext_dipole_e_r0'] = _GenParam(
    name='ext_dipole_e_r0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.001',
)
_sec_el_mag_fld['ext_dipole_e_x0'] = _GenParam(
    name='ext_dipole_e_x0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['ext_e0'] = _GenParam(
    name='ext_e0',
    fortran_type='',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['ext_e_mfunc'] = _GenParam(
    name='ext_e_mfunc',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default='"NO',
)
_sec_el_mag_fld['ext_fld'] = _GenParam(
    name='ext_fld',
    fortran_type='character(len=20)',
    python_type='str',
    default='"none"',
)
_sec_el_mag_fld['init_b0'] = _GenParam(
    name='init_b0',
    fortran_type='',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['init_b_mfunc'] = _GenParam(
    name='init_b_mfunc',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default='"NO',
)
_sec_el_mag_fld['init_dipole_b_m'] = _GenParam(
    name='init_dipole_b_m',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['init_dipole_b_r0'] = _GenParam(
    name='init_dipole_b_r0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.001',
)
_sec_el_mag_fld['init_dipole_b_x0'] = _GenParam(
    name='init_dipole_b_x0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['init_dipole_e_p'] = _GenParam(
    name='init_dipole_e_p',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['init_dipole_e_r0'] = _GenParam(
    name='init_dipole_e_r0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.001',
)
_sec_el_mag_fld['init_dipole_e_x0'] = _GenParam(
    name='init_dipole_e_x0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['init_e0'] = _GenParam(
    name='init_e0',
    fortran_type='',
    python_type='float',
    default='0.0',
)
_sec_el_mag_fld['init_e_mfunc'] = _GenParam(
    name='init_e_mfunc',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default='"NO',
)
_sec_el_mag_fld['smooth_niter'] = _GenParam(
    name='smooth_niter',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_el_mag_fld['smooth_nmax'] = _GenParam(
    name='smooth_nmax',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_el_mag_fld['smooth_type'] = _GenParam(
    name='smooth_type',
    fortran_type='character(len=20)',
    python_type='str',
    default='"none"',
)
_sec_el_mag_fld['solver'] = _GenParam(
    name='solver',
    fortran_type='character(len=20)',
    python_type='str',
    default='"yee"',
)
_sec_el_mag_fld['type_ext_b'] = _GenParam(
    name='type_ext_b',
    fortran_type='',
    python_type='float',
    default='"uniform"',
)
_sec_el_mag_fld['type_ext_e'] = _GenParam(
    name='type_ext_e',
    fortran_type='',
    python_type='float',
    default='"uniform"',
)
_sec_el_mag_fld['type_init_b'] = _GenParam(
    name='type_init_b',
    fortran_type='',
    python_type='float',
    default='"uniform"',
)
_sec_el_mag_fld['type_init_e'] = _GenParam(
    name='type_init_e',
    fortran_type='',
    python_type='float',
    default='"uniform"',
)
GEN_PARAMETERS['el_mag_fld'] = _sec_el_mag_fld

# -- emf_bound (3 parameters)
_sec_emf_bound = {}
_sec_emf_bound['type'] = _GenParam(
    name='type',
    fortran_type='character(20)',
    python_type='str',
    default='"---"',
)
_sec_emf_bound['vpml_bnd_size'] = _GenParam(
    name='vpml_bnd_size',
    fortran_type='integer',
    python_type='int',
    default='p',
)
_sec_emf_bound['vpml_diffuse'] = _GenParam(
    name='vpml_diffuse',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
GEN_PARAMETERS['emf_bound'] = _sec_emf_bound

# -- emf_solver (1 parameters)
_sec_emf_solver = {}
_sec_emf_solver['dummy_'] = _GenParam(
    name='dummy_',
    fortran_type='',
    python_type='float',
    default='None  # huge',
)
GEN_PARAMETERS['emf_solver'] = _sec_emf_solver

# -- grid (16 parameters)
_sec_grid = {}
_sec_grid['balance_on_start'] = _GenParam(
    name='balance_on_start',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_grid['cell_weight'] = _GenParam(
    name='cell_weight',
    fortran_type='real( p_single )',
    python_type='float',
    default='0.0',
)
_sec_grid['coordinates'] = _GenParam(
    name='coordinates',
    fortran_type='character(len=16)',
    python_type='str',
    default='"cartesian"',
)
_sec_grid['io_merge_type'] = _GenParam(
    name='io_merge_type',
    fortran_type='character(len=16)',
    python_type='str',
    default='"point2point"',
)
_sec_grid['io_nmerge'] = _GenParam(
    name='io_nmerge',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_grid['lb_gather'] = _GenParam(
    name='lb_gather',
    fortran_type='character(len=16)',
    python_type='str',
    default='"sum"',
)
_sec_grid['lb_type'] = _GenParam(
    name='lb_type',
    fortran_type='character(len=16)',
    python_type='str',
    default='"none"',
)
_sec_grid['load_balance'] = _GenParam(
    name='load_balance',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_grid['max_imbalance'] = _GenParam(
    name='max_imbalance',
    fortran_type='real( p_single )',
    python_type='float',
    default='0.0',
)
_sec_grid['n_dynamic'] = _GenParam(
    name='n_dynamic',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_grid['ndump_global_load'] = _GenParam(
    name='ndump_global_load',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_grid['ndump_grid_load'] = _GenParam(
    name='ndump_grid_load',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_grid['ndump_node_load'] = _GenParam(
    name='ndump_node_load',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_grid['nx_p'] = _GenParam(
    name='nx_p',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_grid['spatial_loaddensity'] = _GenParam(
    name='spatial_loaddensity',
    fortran_type='character (len=p_max_expr_len)',
    python_type='str',
    default='"NO FUNCTION eEFINEe"',
)
_sec_grid['start_load_balance'] = _GenParam(
    name='start_load_balance',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
GEN_PARAMETERS['grid'] = _sec_grid

# -- neutral (10 parameters)
_sec_neutral = {}
_sec_neutral['den_min'] = _GenParam(
    name='den_min',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_neutral['e_min'] = _GenParam(
    name='e_min',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='1.0e-6',
)
_sec_neutral['if_impact'] = _GenParam(
    name='if_impact',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_neutral['if_tunnel'] = _GenParam(
    name='if_tunnel',
    fortran_type='logical',
    python_type='bool',
    default='True',
)
_sec_neutral['inject_line'] = _GenParam(
    name='inject_line',
    fortran_type='logical',
    python_type='bool',
    default='True',
)
_sec_neutral['ion_param'] = _GenParam(
    name='ion_param',
    fortran_type='',
    python_type='float',
    default='0.0',
)
_sec_neutral['multi_max'] = _GenParam(
    name='multi_max',
    fortran_type='integer',
    python_type='int',
    default='None  # was: min(multi_max, size(neut_param, 2))',
)
_sec_neutral['multi_min'] = _GenParam(
    name='multi_min',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_neutral['name'] = _GenParam(
    name='name',
    fortran_type='character(len=p_max_spname_len)',
    python_type='str',
    default='None  # was: trim(aejustl(eef_name))',
)
_sec_neutral['neutral_gas'] = _GenParam(
    name='neutral_gas',
    fortran_type='',
    python_type='float',
    default='"H"',
)
GEN_PARAMETERS['neutral'] = _sec_neutral

# -- neutral_mov_ions (10 parameters)
_sec_neutral_mov_ions = {}
_sec_neutral_mov_ions['den_min'] = _GenParam(
    name='den_min',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_neutral_mov_ions['e_min'] = _GenParam(
    name='e_min',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='1.0e-6',
)
_sec_neutral_mov_ions['if_impact'] = _GenParam(
    name='if_impact',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_neutral_mov_ions['if_tunnel'] = _GenParam(
    name='if_tunnel',
    fortran_type='logical',
    python_type='bool',
    default='True',
)
_sec_neutral_mov_ions['inject_line'] = _GenParam(
    name='inject_line',
    fortran_type='logical',
    python_type='bool',
    default='True',
)
_sec_neutral_mov_ions['ion_param'] = _GenParam(
    name='ion_param',
    fortran_type='',
    python_type='float',
    default='0.0',
)
_sec_neutral_mov_ions['multi_max'] = _GenParam(
    name='multi_max',
    fortran_type='integer',
    python_type='int',
    default='None  # was: min(multi_max, size(neut_param, 2))',
)
_sec_neutral_mov_ions['multi_min'] = _GenParam(
    name='multi_min',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_neutral_mov_ions['name'] = _GenParam(
    name='name',
    fortran_type='character(len=p_max_spname_len)',
    python_type='str',
    default='None  # was: trim(aejustl(eef_name))',
)
_sec_neutral_mov_ions['neutral_gas'] = _GenParam(
    name='neutral_gas',
    fortran_type='',
    python_type='float',
    default='"H"',
)
GEN_PARAMETERS['neutral_mov_ions'] = _sec_neutral_mov_ions

# -- node_conf (4 parameters)
_sec_node_conf = {}
_sec_node_conf['if_periodic'] = _GenParam(
    name='if_periodic',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_node_conf['n_threads'] = _GenParam(
    name='n_threads',
    fortran_type='integer',
    python_type='int',
    default='None  # was: omp_get_num_threaes()',
)
_sec_node_conf['node_number'] = _GenParam(
    name='node_number',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_node_conf['topology'] = _GenParam(
    name='topology',
    fortran_type='character(len=16)',
    python_type='str',
    default='"mpi"',
)
GEN_PARAMETERS['node_conf'] = _sec_node_conf

# -- num_ene (1 parameters)
_sec_num_ene = {}
_sec_num_ene['num_ene'] = _GenParam(
    name='num_ene',
    fortran_type='integer',
    python_type='int',
    default='17',
)
GEN_PARAMETERS['num_ene'] = _sec_num_ene

# -- particles (15 parameters)
_sec_particles = {}
_sec_particles['grid_center'] = _GenParam(
    name='grid_center',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_particles['interpolation'] = _GenParam(
    name='interpolation',
    fortran_type='integer',
    python_type='int',
    default='"quaeratic"',
)
_sec_particles['low_jay_roundoff'] = _GenParam(
    name='low_jay_roundoff',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_particles['n_ave'] = _GenParam(
    name='n_ave',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_particles['n_tavg'] = _GenParam(
    name='n_tavg',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_particles['ndump_fac'] = _GenParam(
    name='ndump_fac',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_particles['ndump_fac_ave'] = _GenParam(
    name='ndump_fac_ave',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_particles['ndump_fac_ene'] = _GenParam(
    name='ndump_fac_ene',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_particles['ndump_fac_lineout'] = _GenParam(
    name='ndump_fac_lineout',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_particles['num_cathode'] = _GenParam(
    name='num_cathode',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_particles['num_neutral'] = _GenParam(
    name='num_neutral',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_particles['num_neutral_mov_ions'] = _GenParam(
    name='num_neutral_mov_ions',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_particles['num_species'] = _GenParam(
    name='num_species',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_particles['prec'] = _GenParam(
    name='prec',
    fortran_type='integer',
    python_type='int',
    default='p',
)
_sec_particles['reports'] = _GenParam(
    name='reports',
    fortran_type='character( len = p_max_reports_len )',
    python_type='str',
    default='"-"',
)
GEN_PARAMETERS['particles'] = _sec_particles

# -- pgc (8 parameters)
_sec_pgc = {}
_sec_pgc['a0'] = _GenParam(
    name='a0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_pgc['free_stream'] = _GenParam(
    name='free_stream',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_pgc['lon_center'] = _GenParam(
    name='lon_center',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_pgc['omega'] = _GenParam(
    name='omega',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='1.0',
)
_sec_pgc['per_center'] = _GenParam(
    name='per_center',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_pgc['per_focus'] = _GenParam(
    name='per_focus',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='0.0',
)
_sec_pgc['tau'] = _GenParam(
    name='tau',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='1.0',
)
_sec_pgc['w0'] = _GenParam(
    name='w0',
    fortran_type='real(p_k_fld)',
    python_type='float',
    default='1.0',
)
GEN_PARAMETERS['pgc'] = _sec_pgc

# -- piston (9 parameters)
_sec_piston = {}
_sec_piston['dim'] = _GenParam(
    name='dim',
    fortran_type='integer',
    python_type='int',
    default='None  # was: piston_all(pst_ie)%eim',
)
_sec_piston['opacity_factor'] = _GenParam(
    name='opacity_factor',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='1.0',
)
_sec_piston['profile_expression'] = _GenParam(
    name='profile_expression',
    fortran_type='character(p_max_expr_len)',
    python_type='str',
    default='""',
)
_sec_piston['profile_type'] = _GenParam(
    name='profile_type',
    fortran_type='character(20)',
    python_type='str',
    default='"uniform"',
)
_sec_piston['start_pos'] = _GenParam(
    name='start_pos',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0.0',
)
_sec_piston['start_time'] = _GenParam(
    name='start_time',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0.0',
)
_sec_piston['stop_time'] = _GenParam(
    name='stop_time',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0.0',
)
_sec_piston['updown'] = _GenParam(
    name='updown',
    fortran_type='integer',
    python_type='int',
    default='p',
)
_sec_piston['v'] = _GenParam(
    name='v',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0.0',
)
GEN_PARAMETERS['piston'] = _sec_piston

# -- profile (22 parameters)
_sec_profile = {}
_sec_profile['channel_bottom'] = _GenParam(
    name='channel_bottom',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='1.0',
)
_sec_profile['channel_center'] = _GenParam(
    name='channel_center',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='None  # was: -huge( 1.0_p_k_part )',
)
_sec_profile['channel_depth'] = _GenParam(
    name='channel_depth',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='None  # was: -huge( 1.0_p_k_part )',
)
_sec_profile['channel_dir'] = _GenParam(
    name='channel_dir',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_profile['channel_pos'] = _GenParam(
    name='channel_pos',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='None  # was: -huge( 1.0_p_k_part )',
)
_sec_profile['channel_r0'] = _GenParam(
    name='channel_r0',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='None  # was: -huge( 1.0_p_k_part )',
)
_sec_profile['channel_size'] = _GenParam(
    name='channel_size',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='None  # was: -huge( 1.0_p_k_part )',
)
_sec_profile['channel_wall'] = _GenParam(
    name='channel_wall',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0.0',
)
_sec_profile['den_min'] = _GenParam(
    name='den_min',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0',
)
_sec_profile['density'] = _GenParam(
    name='density',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='1.0',
)
_sec_profile['fx'] = _GenParam(
    name='fx',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0.0',
)
_sec_profile['gauss_center'] = _GenParam(
    name='gauss_center',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0.0',
)
_sec_profile['gauss_n_sigma'] = _GenParam(
    name='gauss_n_sigma',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_profile['gauss_range'] = _GenParam(
    name='gauss_range',
    fortran_type='real(p_k_part)',
    python_type='float',
    default=None,
)
_sec_profile['gauss_sigma'] = _GenParam(
    name='gauss_sigma',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='None  # was: huge( 1.0_p_k_part )',
)
_sec_profile['math_func_expr'] = _GenParam(
    name='math_func_expr',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default='"NO',
)
_sec_profile['num_x'] = _GenParam(
    name='num_x',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_profile['profile_type'] = _GenParam(
    name='profile_type',
    fortran_type='character(20)',
    python_type='str',
    default='"eefault"',
)
_sec_profile['sample_rate'] = _GenParam(
    name='sample_rate',
    fortran_type='integer',
    python_type='int',
    default='32',
)
_sec_profile['sphere_center'] = _GenParam(
    name='sphere_center',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0.0',
)
_sec_profile['sphere_radius'] = _GenParam(
    name='sphere_radius',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0.0',
)
_sec_profile['x'] = _GenParam(
    name='x',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='None  # was: - huge( 1.0_p_k_part )',
)
GEN_PARAMETERS['profile'] = _sec_profile

# -- restart (5 parameters)
_sec_restart = {}
_sec_restart['debug_iter'] = _GenParam(
    name='debug_iter',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_restart['if_remold'] = _GenParam(
    name='if_remold',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_restart['if_restart'] = _GenParam(
    name='if_restart',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_restart['ndump_fac'] = _GenParam(
    name='ndump_fac',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_restart['ndump_time'] = _GenParam(
    name='ndump_time',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
GEN_PARAMETERS['restart'] = _sec_restart

# -- sdist (6 parameters)
_sec_sdist = {}
_sec_sdist['gauss_mu'] = _GenParam(
    name='gauss_mu',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: (/-huge(1.0_p_eouble), 0.0_p_eouble, 0.0_p_eouble/)',
)
_sec_sdist['gauss_theta'] = _GenParam(
    name='gauss_theta',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_sdist['n_dirs'] = _GenParam(
    name='n_dirs',
    fortran_type='integer',
    python_type='int',
    default='species%seist%n',
)
_sec_sdist['pdf'] = _GenParam(
    name='pdf',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: 0.0_p_eouble; pef(1) = 1.0',
)
_sec_sdist['sdir'] = _GenParam(
    name='sdir',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: 0.0_p_eouble; seir(1,1) = 1.0',
)
_sec_sdist['sdist_type'] = _GenParam(
    name='sdist_type',
    fortran_type='character(len=20)',
    python_type='str',
    default='"isotropic"',
)
GEN_PARAMETERS['sdist'] = _sec_sdist

# -- simulation (15 parameters)
_sec_simulation = {}
_sec_simulation['algorithm'] = _GenParam(
    name='algorithm',
    fortran_type='',
    python_type='float',
    default='"staneare"',
)
_sec_simulation['enforce_rng_constancy'] = _GenParam(
    name='enforce_rng_constancy',
    fortran_type='',
    python_type='float',
    default='False',
)
_sec_simulation['file_format'] = _GenParam(
    name='file_format',
    fortran_type='character(len=20)',
    python_type='str',
    default="'zef'",
)
_sec_simulation['gamma'] = _GenParam(
    name='gamma',
    fortran_type='',
    python_type='float',
    default='1',
)
_sec_simulation['n0'] = _GenParam(
    name='n0',
    fortran_type='',
    python_type='float',
    default='0',
)
_sec_simulation['ndump_prof'] = _GenParam(
    name='ndump_prof',
    fortran_type='',
    python_type='float',
    default='0',
)
_sec_simulation['omega_p0'] = _GenParam(
    name='omega_p0',
    fortran_type='real(p_double)',
    python_type='float',
    default='0',
)
_sec_simulation['parallel_io'] = _GenParam(
    name='parallel_io',
    fortran_type='character(len=20)',
    python_type='str',
    default="'mpi'",
)
_sec_simulation['prof_end'] = _GenParam(
    name='prof_end',
    fortran_type='',
    python_type='float',
    default='None  # was: huge(prof_start)',
)
_sec_simulation['prof_start'] = _GenParam(
    name='prof_start',
    fortran_type='',
    python_type='float',
    default='-1',
)
_sec_simulation['random_algorithm'] = _GenParam(
    name='random_algorithm',
    fortran_type='',
    python_type='float',
    default="'eefault'",
)
_sec_simulation['random_seed'] = _GenParam(
    name='random_seed',
    fortran_type='',
    python_type='float',
    default='0',
)
_sec_simulation['wall_clock_check'] = _GenParam(
    name='wall_clock_check',
    fortran_type='',
    python_type='float',
    default='-1',
)
_sec_simulation['wall_clock_checkpoint'] = _GenParam(
    name='wall_clock_checkpoint',
    fortran_type='',
    python_type='float',
    default='True',
)
_sec_simulation['wall_clock_limit'] = _GenParam(
    name='wall_clock_limit',
    fortran_type='',
    python_type='float',
    default='""',
)
GEN_PARAMETERS['simulation'] = _sec_simulation

# -- smooth (7 parameters)
_sec_smooth = {}
_sec_smooth['digital_A'] = _GenParam(
    name='digital_A',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0e0)',
)
_sec_smooth['digital_fc'] = _GenParam(
    name='digital_fc',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0e0)',
)
_sec_smooth['laserkdx_dir'] = _GenParam(
    name='laserkdx_dir',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_smooth['laserkdx_omega0'] = _GenParam(
    name='laserkdx_omega0',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1.0',
)
_sec_smooth['order'] = _GenParam(
    name='order',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_smooth['swfj'] = _GenParam(
    name='swfj',
    fortran_type='real(p_double)',
    python_type='float',
    default='1',
)
_sec_smooth['type'] = _GenParam(
    name='type',
    fortran_type='character(len = 20)',
    python_type='str',
    default='"none"',
)
GEN_PARAMETERS['smooth'] = _sec_smooth

# -- space (4 parameters)
_sec_space = {}
_sec_space['if_move'] = _GenParam(
    name='if_move',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_space['move_u'] = _GenParam(
    name='move_u',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1.0',
)
_sec_space['xmax'] = _GenParam(
    name='xmax',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_space['xmin'] = _GenParam(
    name='xmin',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
GEN_PARAMETERS['space'] = _sec_space

# -- spe_bound (4 parameters)
_sec_spe_bound = {}
_sec_spe_bound['thermal_type'] = _GenParam(
    name='thermal_type',
    fortran_type='character(len=20)',
    python_type='str',
    default='"thermal"',
)
_sec_spe_bound['type'] = _GenParam(
    name='type',
    fortran_type='character(20)',
    python_type='str',
    default='"---"',
)
_sec_spe_bound['ufl_bnd'] = _GenParam(
    name='ufl_bnd',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0',
)
_sec_spe_bound['uth_bnd'] = _GenParam(
    name='uth_bnd',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0',
)
GEN_PARAMETERS['spe_bound'] = _sec_spe_bound

# -- species (18 parameters)
_sec_species = {}
_sec_species['add_tag'] = _GenParam(
    name='add_tag',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_species['free_stream'] = _GenParam(
    name='free_stream',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_species['if_collide'] = _GenParam(
    name='if_collide',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_species['if_like_collide'] = _GenParam(
    name='if_like_collide',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_species['init_fields'] = _GenParam(
    name='init_fields',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_species['init_type'] = _GenParam(
    name='init_type',
    fortran_type='character(len = 16)',
    python_type='str',
    default='"staneare"',
)
_sec_species['iter_tol'] = _GenParam(
    name='iter_tol',
    fortran_type='real(p_double)',
    python_type='float',
    default='1.0e-3',
)
_sec_species['n_sort'] = _GenParam(
    name='n_sort',
    fortran_type='integer',
    python_type='int',
    default='25',
)
_sec_species['name'] = _GenParam(
    name='name',
    fortran_type='character(len = p_max_spname_len)',
    python_type='str',
    default='None  # was: trim(aejustl(eef_name))',
)
_sec_species['num_par_max'] = _GenParam(
    name='num_par_max',
    fortran_type='integer',
    python_type='int',
    default='this%num',
)
_sec_species['num_par_x'] = _GenParam(
    name='num_par_x',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_species['num_pistons'] = _GenParam(
    name='num_pistons',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_species['push_start_time'] = _GenParam(
    name='push_start_time',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1.0',
)
_sec_species['push_type'] = _GenParam(
    name='push_type',
    fortran_type='integer',
    python_type='int',
    default='this%push',
)
_sec_species['q_real'] = _GenParam(
    name='q_real',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0',
)
_sec_species['rad_react'] = _GenParam(
    name='rad_react',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_species['rqm'] = _GenParam(
    name='rqm',
    fortran_type='real(p_k_part)',
    python_type='float',
    default='0',
)
_sec_species['tot_par_x'] = _GenParam(
    name='tot_par_x',
    fortran_type='',
    python_type='float',
    default='-1',
)
GEN_PARAMETERS['species'] = _sec_species

# -- test_set (8 parameters)
_sec_test_set = {}
_sec_test_set['format'] = _GenParam(
    name='format',
    fortran_type='character(len = 16)',
    python_type='str',
    default='"-"',
)
_sec_test_set['grid'] = _GenParam(
    name='grid',
    fortran_type='character(len = 16)',
    python_type='str',
    default='"-"',
)
_sec_test_set['keepFiles'] = _GenParam(
    name='keepFiles',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_test_set['merge_type'] = _GenParam(
    name='merge_type',
    fortran_type='character(len = 16)',
    python_type='str',
    default='"-"',
)
_sec_test_set['n_merge'] = _GenParam(
    name='n_merge',
    fortran_type='character(len = 16)',
    python_type='str',
    default='"-"',
)
_sec_test_set['parallel_io'] = _GenParam(
    name='parallel_io',
    fortran_type='character(len = 16)',
    python_type='str',
    default='"-"',
)
_sec_test_set['path'] = _GenParam(
    name='path',
    fortran_type='character(len=1024)',
    python_type='str',
    default="''",
)
_sec_test_set['repeat'] = _GenParam(
    name='repeat',
    fortran_type='integer',
    python_type='int',
    default='3',
)
GEN_PARAMETERS['test_set'] = _sec_test_set

# -- time (2 parameters)
_sec_time = {}
_sec_time['tmax'] = _GenParam(
    name='tmax',
    fortran_type='real(p_double)',
    python_type='float',
    default='this%tmax',
)
_sec_time['tmin'] = _GenParam(
    name='tmin',
    fortran_type='real(p_double)',
    python_type='float',
    default='this%tmin',
)
GEN_PARAMETERS['time'] = _sec_time

# -- time_step (3 parameters)
_sec_time_step = {}
_sec_time_step['dt'] = _GenParam(
    name='dt',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_time_step['dump_start'] = _GenParam(
    name='dump_start',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_time_step['ndump'] = _GenParam(
    name='ndump',
    fortran_type='integer',
    python_type='int',
    default='0',
)
GEN_PARAMETERS['time_step'] = _sec_time_step

# -- udist (19 parameters)
_sec_udist = {}
_sec_udist['math_func_use_thermal'] = _GenParam(
    name='math_func_use_thermal',
    fortran_type='logical',
    python_type='bool',
    default=None,
)
_sec_udist['math_func_uth'] = _GenParam(
    name='math_func_uth',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default=None,
)
_sec_udist['n_accelerate'] = _GenParam(
    name='n_accelerate',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_udist['n_accelerate_type'] = _GenParam(
    name='n_accelerate_type',
    fortran_type='character(len=20)',
    python_type='str',
    default='"linear"',
)
_sec_udist['n_q_incr'] = _GenParam(
    name='n_q_incr',
    fortran_type='integer',
    python_type='int',
    default='-1',
)
_sec_udist['n_q_incr_type'] = _GenParam(
    name='n_q_incr_type',
    fortran_type='character(len=20)',
    python_type='str',
    default='"linear"',
)
_sec_udist['relmax_T'] = _GenParam(
    name='relmax_T',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_udist['relmax_umax'] = _GenParam(
    name='relmax_umax',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1',
)
_sec_udist['spatial_ufl'] = _GenParam(
    name='spatial_ufl',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default=None,
)
_sec_udist['spatial_uth'] = _GenParam(
    name='spatial_uth',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default=None,
)
_sec_udist['ufl'] = _GenParam(
    name='ufl',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_udist['umax'] = _GenParam(
    name='umax',
    fortran_type='real(p_double)',
    python_type='float',
    default='0',
)
_sec_udist['umin'] = _GenParam(
    name='umin',
    fortran_type='real(p_double)',
    python_type='float',
    default='0',
)
_sec_udist['use_classical_uadd'] = _GenParam(
    name='use_classical_uadd',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_udist['use_particle_uacc'] = _GenParam(
    name='use_particle_uacc',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_udist['use_spatial_ufl'] = _GenParam(
    name='use_spatial_ufl',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_udist['use_spatial_uth'] = _GenParam(
    name='use_spatial_uth',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_udist['uth'] = _GenParam(
    name='uth',
    fortran_type='real(p_double)',
    python_type='float',
    default='0',
)
_sec_udist['uth_type'] = _GenParam(
    name='uth_type',
    fortran_type='character(len=20)',
    python_type='str',
    default='"thermal"',
)
GEN_PARAMETERS['udist'] = _sec_udist

# -- zpulse (39 parameters)
_sec_zpulse = {}
_sec_zpulse['a0'] = _GenParam(
    name='a0',
    fortran_type='real(p_double)',
    python_type='float',
    default='1.0',
)
_sec_zpulse['b_type'] = _GenParam(
    name='b_type',
    fortran_type='character(len=16)',
    python_type='str',
    default='"normal"',
)
_sec_zpulse['chirp_coefs'] = _GenParam(
    name='chirp_coefs',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['chirp_order'] = _GenParam(
    name='chirp_order',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse['direction'] = _GenParam(
    name='direction',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_zpulse['if_launch'] = _GenParam(
    name='if_launch',
    fortran_type='logical',
    python_type='bool',
    default='True',
)
_sec_zpulse['launch_time'] = _GenParam(
    name='launch_time',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['lon_duration'] = _GenParam(
    name='lon_duration',
    fortran_type='real(p_double)',
    python_type='float',
    default='this%lon',
)
_sec_zpulse['lon_fall'] = _GenParam(
    name='lon_fall',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['lon_flat'] = _GenParam(
    name='lon_flat',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['lon_fwhm'] = _GenParam(
    name='lon_fwhm',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1.0',
)
_sec_zpulse['lon_math_func'] = _GenParam(
    name='lon_math_func',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default='"NO',
)
_sec_zpulse['lon_range'] = _GenParam(
    name='lon_range',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse['lon_rise'] = _GenParam(
    name='lon_rise',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['lon_start'] = _GenParam(
    name='lon_start',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse['lon_tilt'] = _GenParam(
    name='lon_tilt',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['lon_type'] = _GenParam(
    name='lon_type',
    fortran_type='character(len=16)',
    python_type='str',
    default='"polynomial"',
)
_sec_zpulse['lon_x0'] = _GenParam(
    name='lon_x0',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse['no_div_corr'] = _GenParam(
    name='no_div_corr',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_zpulse['omega0'] = _GenParam(
    name='omega0',
    fortran_type='real(p_double)',
    python_type='float',
    default='10.0',
)
_sec_zpulse['per_0clip'] = _GenParam(
    name='per_0clip',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_zpulse['per_asym_trans'] = _GenParam(
    name='per_asym_trans',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['per_center'] = _GenParam(
    name='per_center',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse['per_chirp_coefs'] = _GenParam(
    name='per_chirp_coefs',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['per_chirp_order'] = _GenParam(
    name='per_chirp_order',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse['per_focus'] = _GenParam(
    name='per_focus',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse['per_focus_asym'] = _GenParam(
    name='per_focus_asym',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse['per_fwhm'] = _GenParam(
    name='per_fwhm',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['per_fwhm_asym'] = _GenParam(
    name='per_fwhm_asym',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['per_kt'] = _GenParam(
    name='per_kt',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['per_n'] = _GenParam(
    name='per_n',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse['per_tem_mode'] = _GenParam(
    name='per_tem_mode',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse['per_type'] = _GenParam(
    name='per_type',
    fortran_type='character(len=16)',
    python_type='str',
    default='"plane"',
)
_sec_zpulse['per_w0'] = _GenParam(
    name='per_w0',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['per_w0_asym'] = _GenParam(
    name='per_w0_asym',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['phase'] = _GenParam(
    name='phase',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse['pol'] = _GenParam(
    name='pol',
    fortran_type='real(p_double)',
    python_type='float',
    default='90.0',
)
_sec_zpulse['pol_type'] = _GenParam(
    name='pol_type',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse['propagation'] = _GenParam(
    name='propagation',
    fortran_type='character(len=16)',
    python_type='str',
    default='"forware"',
)
GEN_PARAMETERS['zpulse'] = _sec_zpulse

# -- zpulse_point (17 parameters)
_sec_zpulse_point = {}
_sec_zpulse_point['a0'] = _GenParam(
    name='a0',
    fortran_type='real(p_double)',
    python_type='float',
    default='1.0',
)
_sec_zpulse_point['chirp_coefs'] = _GenParam(
    name='chirp_coefs',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_point['chirp_order'] = _GenParam(
    name='chirp_order',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse_point['if_launch'] = _GenParam(
    name='if_launch',
    fortran_type='logical',
    python_type='bool',
    default='True',
)
_sec_zpulse_point['launch_time'] = _GenParam(
    name='launch_time',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_point['omega0'] = _GenParam(
    name='omega0',
    fortran_type='real(p_double)',
    python_type='float',
    default='10.0',
)
_sec_zpulse_point['phase'] = _GenParam(
    name='phase',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_point['point_pos'] = _GenParam(
    name='point_pos',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse_point['pol_vector'] = _GenParam(
    name='pol_vector',
    fortran_type='real(p_double)',
    python_type='float',
    default=None,
)
_sec_zpulse_point['tenv_duration'] = _GenParam(
    name='tenv_duration',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_point['tenv_fall'] = _GenParam(
    name='tenv_fall',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_point['tenv_flat'] = _GenParam(
    name='tenv_flat',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_point['tenv_fwhm'] = _GenParam(
    name='tenv_fwhm',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1.0',
)
_sec_zpulse_point['tenv_math_func'] = _GenParam(
    name='tenv_math_func',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default='"NO',
)
_sec_zpulse_point['tenv_range'] = _GenParam(
    name='tenv_range',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse_point['tenv_rise'] = _GenParam(
    name='tenv_rise',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_point['tenv_type'] = _GenParam(
    name='tenv_type',
    fortran_type='character(len=16)',
    python_type='str',
    default='"polynomial"',
)
GEN_PARAMETERS['zpulse_point'] = _sec_zpulse_point

# -- zpulse_speckle (52 parameters)
_sec_zpulse_speckle = {}
_sec_zpulse_speckle['!per_fwhm'] = _GenParam(
    name='!per_fwhm',
    fortran_type='',
    python_type='float',
    default=None,
)
_sec_zpulse_speckle['!per_n'] = _GenParam(
    name='!per_n',
    fortran_type='',
    python_type='float',
    default=None,
)
_sec_zpulse_speckle['!per_w0_asym'] = _GenParam(
    name='!per_w0_asym',
    fortran_type='',
    python_type='float',
    default=None,
)
_sec_zpulse_speckle['a0'] = _GenParam(
    name='a0',
    fortran_type='real(p_double)',
    python_type='float',
    default='1.0',
)
_sec_zpulse_speckle['bandwidth_type'] = _GenParam(
    name='bandwidth_type',
    fortran_type='Character(len=16)',
    python_type='str',
    default="'lorentzian'",
)
_sec_zpulse_speckle['chirp_coefs'] = _GenParam(
    name='chirp_coefs',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['chirp_order'] = _GenParam(
    name='chirp_order',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse_speckle['chirp_period'] = _GenParam(
    name='chirp_period',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: huge(1.0_p_eouble)',
)
_sec_zpulse_speckle['color_cycle'] = _GenParam(
    name='color_cycle',
    fortran_type='integer',
    python_type='int',
    default='1.0',
)
_sec_zpulse_speckle['direction'] = _GenParam(
    name='direction',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_zpulse_speckle['dt_update_pol'] = _GenParam(
    name='dt_update_pol',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: - huge(1.0_p_eouble)',
)
_sec_zpulse_speckle['dt_update_speckle'] = _GenParam(
    name='dt_update_speckle',
    fortran_type='real(p_double)',
    python_type='float',
    default='this%stue',
)
_sec_zpulse_speckle['duty_cycle'] = _GenParam(
    name='duty_cycle',
    fortran_type='real(p_double)',
    python_type='float',
    default='50.0',
)
_sec_zpulse_speckle['fm'] = _GenParam(
    name='fm',
    fortran_type='real(p_double)',
    python_type='float',
    default='1.0',
)
_sec_zpulse_speckle['if_dump_speckle'] = _GenParam(
    name='if_dump_speckle',
    fortran_type='logical',
    python_type='bool',
    default='False',
)
_sec_zpulse_speckle['if_launch'] = _GenParam(
    name='if_launch',
    fortran_type='logical',
    python_type='bool',
    default='True',
)
_sec_zpulse_speckle['laser_bandwidth'] = _GenParam(
    name='laser_bandwidth',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: laser_banewieth * sqrt(8.0)',
)
_sec_zpulse_speckle['launch_time'] = _GenParam(
    name='launch_time',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['lon_focus'] = _GenParam(
    name='lon_focus',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['n_speckle'] = _GenParam(
    name='n_speckle',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_zpulse_speckle['nfm'] = _GenParam(
    name='nfm',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_zpulse_speckle['omega0'] = _GenParam(
    name='omega0',
    fortran_type='real(p_double)',
    python_type='float',
    default='1.0',
)
_sec_zpulse_speckle['per_0clip'] = _GenParam(
    name='per_0clip',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_zpulse_speckle['per_asym_trans'] = _GenParam(
    name='per_asym_trans',
    fortran_type='',
    python_type='float',
    default=None,
)
_sec_zpulse_speckle['per_center'] = _GenParam(
    name='per_center',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: - huge(1.0_p_eouble)',
)
_sec_zpulse_speckle['per_focus_asym'] = _GenParam(
    name='per_focus_asym',
    fortran_type='',
    python_type='float',
    default=None,
)
_sec_zpulse_speckle['per_fwhm_asym'] = _GenParam(
    name='per_fwhm_asym',
    fortran_type='',
    python_type='float',
    default=None,
)
_sec_zpulse_speckle['per_kt'] = _GenParam(
    name='per_kt',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['per_tem_mode'] = _GenParam(
    name='per_tem_mode',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse_speckle['per_w0'] = _GenParam(
    name='per_w0',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['phase'] = _GenParam(
    name='phase',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['phasemod_amplitude'] = _GenParam(
    name='phasemod_amplitude',
    fortran_type='real(p_double)',
    python_type='float',
    default='2 * PI',
)
_sec_zpulse_speckle['pol'] = _GenParam(
    name='pol',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['pol_stepping'] = _GenParam(
    name='pol_stepping',
    fortran_type='real(p_double)',
    python_type='float',
    default='90.0',
)
_sec_zpulse_speckle['pol_type'] = _GenParam(
    name='pol_type',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse_speckle['propagation'] = _GenParam(
    name='propagation',
    fortran_type='character(len=16)',
    python_type='str',
    default='"forware"',
)
_sec_zpulse_speckle['recurrence_time'] = _GenParam(
    name='recurrence_time',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: - huge(1.0_p_eouble)',
)
_sec_zpulse_speckle['rseed_phase'] = _GenParam(
    name='rseed_phase',
    fortran_type='integer',
    python_type='int',
    default='p',
)
_sec_zpulse_speckle['rseed_stud'] = _GenParam(
    name='rseed_stud',
    fortran_type='integer',
    python_type='int',
    default='p',
)
_sec_zpulse_speckle['spatial_tilt'] = _GenParam(
    name='spatial_tilt',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['speckle_type'] = _GenParam(
    name='speckle_type',
    fortran_type='Character(len=16)',
    python_type='str',
    default="'cpurp'",
)
_sec_zpulse_speckle['stud_duration'] = _GenParam(
    name='stud_duration',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: - huge(1.0_p_eouble)',
)
_sec_zpulse_speckle['stud_jitter'] = _GenParam(
    name='stud_jitter',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['tenv_duration'] = _GenParam(
    name='tenv_duration',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['tenv_fall'] = _GenParam(
    name='tenv_fall',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['tenv_flat'] = _GenParam(
    name='tenv_flat',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['tenv_fwhm'] = _GenParam(
    name='tenv_fwhm',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1.0',
)
_sec_zpulse_speckle['tenv_math_func'] = _GenParam(
    name='tenv_math_func',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default='"NO',
)
_sec_zpulse_speckle['tenv_range'] = _GenParam(
    name='tenv_range',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: - huge(1.0_p_eouble)',
)
_sec_zpulse_speckle['tenv_rise'] = _GenParam(
    name='tenv_rise',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_speckle['tenv_type'] = _GenParam(
    name='tenv_type',
    fortran_type='character(len=16)',
    python_type='str',
    default='"polynomial"',
)
_sec_zpulse_speckle['theta'] = _GenParam(
    name='theta',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
GEN_PARAMETERS['zpulse_speckle'] = _sec_zpulse_speckle

# -- zpulse_wall (35 parameters)
_sec_zpulse_wall = {}
_sec_zpulse_wall['a0'] = _GenParam(
    name='a0',
    fortran_type='real(p_double)',
    python_type='float',
    default='1.0',
)
_sec_zpulse_wall['chirp_coefs'] = _GenParam(
    name='chirp_coefs',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['chirp_order'] = _GenParam(
    name='chirp_order',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse_wall['direction'] = _GenParam(
    name='direction',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_zpulse_wall['if_launch'] = _GenParam(
    name='if_launch',
    fortran_type='logical',
    python_type='bool',
    default='True',
)
_sec_zpulse_wall['launch_time'] = _GenParam(
    name='launch_time',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['omega0'] = _GenParam(
    name='omega0',
    fortran_type='real(p_double)',
    python_type='float',
    default='10.0',
)
_sec_zpulse_wall['per_0clip'] = _GenParam(
    name='per_0clip',
    fortran_type='integer',
    python_type='int',
    default='1',
)
_sec_zpulse_wall['per_asym_trans'] = _GenParam(
    name='per_asym_trans',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['per_center'] = _GenParam(
    name='per_center',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse_wall['per_chirp_coefs'] = _GenParam(
    name='per_chirp_coefs',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['per_chirp_order'] = _GenParam(
    name='per_chirp_order',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse_wall['per_focus'] = _GenParam(
    name='per_focus',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse_wall['per_focus_asym'] = _GenParam(
    name='per_focus_asym',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse_wall['per_fwhm'] = _GenParam(
    name='per_fwhm',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['per_fwhm_asym'] = _GenParam(
    name='per_fwhm_asym',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['per_kt'] = _GenParam(
    name='per_kt',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['per_n'] = _GenParam(
    name='per_n',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse_wall['per_tem_mode'] = _GenParam(
    name='per_tem_mode',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse_wall['per_type'] = _GenParam(
    name='per_type',
    fortran_type='character(len=16)',
    python_type='str',
    default='"plane"',
)
_sec_zpulse_wall['per_w0'] = _GenParam(
    name='per_w0',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['per_w0_asym'] = _GenParam(
    name='per_w0_asym',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['phase'] = _GenParam(
    name='phase',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['pol'] = _GenParam(
    name='pol',
    fortran_type='real(p_double)',
    python_type='float',
    default='90.0',
)
_sec_zpulse_wall['pol_type'] = _GenParam(
    name='pol_type',
    fortran_type='integer',
    python_type='int',
    default='0',
)
_sec_zpulse_wall['propagation'] = _GenParam(
    name='propagation',
    fortran_type='character(len=16)',
    python_type='str',
    default='"forware"',
)
_sec_zpulse_wall['tenv_duration'] = _GenParam(
    name='tenv_duration',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['tenv_fall'] = _GenParam(
    name='tenv_fall',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['tenv_flat'] = _GenParam(
    name='tenv_flat',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['tenv_fwhm'] = _GenParam(
    name='tenv_fwhm',
    fortran_type='real(p_double)',
    python_type='float',
    default='-1.0',
)
_sec_zpulse_wall['tenv_math_func'] = _GenParam(
    name='tenv_math_func',
    fortran_type='character(len = p_max_expr_len)',
    python_type='str',
    default='"NO',
)
_sec_zpulse_wall['tenv_range'] = _GenParam(
    name='tenv_range',
    fortran_type='real(p_double)',
    python_type='float',
    default='None  # was: -huge(1.0_p_eouble)',
)
_sec_zpulse_wall['tenv_rise'] = _GenParam(
    name='tenv_rise',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['tenv_tilt'] = _GenParam(
    name='tenv_tilt',
    fortran_type='real(p_double)',
    python_type='float',
    default='0.0',
)
_sec_zpulse_wall['tenv_type'] = _GenParam(
    name='tenv_type',
    fortran_type='character(len=16)',
    python_type='str',
    default='"polynomial"',
)
GEN_PARAMETERS['zpulse_wall'] = _sec_zpulse_wall
