"""Auto-generated diagnostic quantity lists from OSIRIS Fortran source.

Generated by: osiris-toolkit sync extract
DO NOT EDIT MANUALLY. Changes will be overwritten.
"""

from __future__ import annotations

# diagnostic_type -> list of quantity name strings
GEN_QUANTITIES: dict[str, list[str]] = {}

# CHARGE: 3 quantities
GEN_QUANTITIES['CHARGE'] = [
    'charge',
    'charge_htc',
    'dcharge_dt',
]

# CURRENT: 4 quantities
GEN_QUANTITIES['CURRENT'] = [
    'j1',
    'j2',
    'j3',
    'div_j',
]

# DENSITY: 9 quantities
GEN_QUANTITIES['DENSITY'] = [
    'charge',
    'm',
    'ene',
    'q1',
    'q2',
    'q3',
    'j1',
    'j2',
    'j3',
]

# EMF: 34 quantities
GEN_QUANTITIES['EMF'] = [
    'e1',
    'e2',
    'e3',
    'b1',
    'b2',
    'b3',
    'ext_e1',
    'ext_e2',
    'ext_e3',
    'ext_b1',
    'ext_b2',
    'ext_b3',
    'part_e1',
    'part_e2',
    'part_e3',
    'part_b1',
    'part_b2',
    'part_b3',
    'ene_e1',
    'ene_e2',
    'ene_e3',
    'ene_b1',
    'ene_b2',
    'ene_b3',
    'ene_e',
    'ene_b',
    'ene_emf',
    'div_e',
    'div_b',
    'psi',
    'chargecons',
    's1',
    's2',
    's3',
]

# NEUTRAL: 2 quantities
GEN_QUANTITIES['NEUTRAL'] = [
    'ion_charge',
    'neut_den',
]

# UDIST: 12 quantities
GEN_QUANTITIES['UDIST'] = [
    'ufl1',
    'ufl2',
    'ufl3',
    'uth1',
    'uth2',
    'uth3',
    'T11',
    'T22',
    'T33',
    'T12',
    'T13',
    'T23',
]
