"""Auto-generated section list from OSIRIS Fortran get_namelist calls.

Generated by: osiris-toolkit sync extract
DO NOT EDIT MANUALLY. Changes will be overwritten.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class _GenSection:
    """One auto-generated section entry."""
    name: str          # section name (without nl_ prefix)
    nl_name: str       # full namelist name (with nl_ prefix)


# All sections found in Fortran source
GEN_SECTIONS: list[_GenSection] = []

GEN_SECTIONS.append(_GenSection(name='antenna', nl_name='nl_antenna'))
GEN_SECTIONS.append(_GenSection(name='antenna_array', nl_name='nl_antenna_array'))
GEN_SECTIONS.append(_GenSection(name='cathode', nl_name='nl_cathode'))
GEN_SECTIONS.append(_GenSection(name='collisions', nl_name='nl_collisions'))
GEN_SECTIONS.append(_GenSection(name='cross', nl_name='nl_cross'))
GEN_SECTIONS.append(_GenSection(name='current', nl_name='nl_current'))
GEN_SECTIONS.append(_GenSection(name='diag_current', nl_name='nl_diag_current'))
GEN_SECTIONS.append(_GenSection(name='diag_emf', nl_name='nl_diag_emf'))
GEN_SECTIONS.append(_GenSection(name='diag_neutral', nl_name='nl_diag_neutral'))
GEN_SECTIONS.append(_GenSection(name='diag_species', nl_name='nl_diag_species'))
GEN_SECTIONS.append(_GenSection(name='el_mag_fld', nl_name='nl_el_mag_fld'))
GEN_SECTIONS.append(_GenSection(name='emf_bound', nl_name='nl_emf_bound'))
GEN_SECTIONS.append(_GenSection(name='emf_solver', nl_name='nl_emf_solver'))
GEN_SECTIONS.append(_GenSection(name='grid', nl_name='nl_grid'))
GEN_SECTIONS.append(_GenSection(name='neutral', nl_name='nl_neutral'))
GEN_SECTIONS.append(_GenSection(name='neutral_mov_ions', nl_name='nl_neutral_mov_ions'))
GEN_SECTIONS.append(_GenSection(name='node_conf', nl_name='nl_node_conf'))
GEN_SECTIONS.append(_GenSection(name='num_ene', nl_name='nl_num_ene'))
GEN_SECTIONS.append(_GenSection(name='particles', nl_name='nl_particles'))
GEN_SECTIONS.append(_GenSection(name='pgc', nl_name='nl_pgc'))
GEN_SECTIONS.append(_GenSection(name='piston', nl_name='nl_piston'))
GEN_SECTIONS.append(_GenSection(name='profile', nl_name='nl_profile'))
GEN_SECTIONS.append(_GenSection(name='restart', nl_name='nl_restart'))
GEN_SECTIONS.append(_GenSection(name='sdist', nl_name='nl_sdist'))
GEN_SECTIONS.append(_GenSection(name='simulation', nl_name='nl_simulation'))
GEN_SECTIONS.append(_GenSection(name='smooth', nl_name='nl_smooth'))
GEN_SECTIONS.append(_GenSection(name='space', nl_name='nl_space'))
GEN_SECTIONS.append(_GenSection(name='spe_bound', nl_name='nl_spe_bound'))
GEN_SECTIONS.append(_GenSection(name='species', nl_name='nl_species'))
GEN_SECTIONS.append(_GenSection(name='test_set', nl_name='nl_test_set'))
GEN_SECTIONS.append(_GenSection(name='time', nl_name='nl_time'))
GEN_SECTIONS.append(_GenSection(name='time_step', nl_name='nl_time_step'))
GEN_SECTIONS.append(_GenSection(name='udist', nl_name='nl_udist'))
GEN_SECTIONS.append(_GenSection(name='zpulse', nl_name='nl_zpulse'))
GEN_SECTIONS.append(_GenSection(name='zpulse_point', nl_name='nl_zpulse_point'))
GEN_SECTIONS.append(_GenSection(name='zpulse_speckle', nl_name='nl_zpulse_speckle'))
GEN_SECTIONS.append(_GenSection(name='zpulse_wall', nl_name='nl_zpulse_wall'))

# Section names only (for quick reference)
SECTION_NAMES: list[str] = [
    'current',
    'diag_current',
    'emf_bound',
    'diag_emf',
    'el_mag_fld',
    'emf_solver',
    'grid',
    'test_set',
    'pgc',
    'antenna',
    'antenna_array',
    'cathode',
    'num_ene',
    'cross',
    'diag_neutral',
    'simulation',
    'node_conf',
    'neutral',
    'neutral_mov_ions',
    'space',
    'time',
    'time_step',
    'particles',
    'restart',
    'diag_species',
    'spe_bound',
    'collisions',
    'piston',
    'sdist',
    'udist',
    'species',
    'profile',
    'smooth',
    'zpulse_point',
    'zpulse_speckle',
    'zpulse',
    'zpulse_wall',
]
